# Static configuration — requires restart to reload
# sconf format: uses tabs for indentation
Hostname: mail.alias.id

TLS:
	ACME:
		letsencrypt:
			DirectoryURL: https://acme-v02.api.letsencrypt.org/directory
			ContactEmail: admin@alias.id

Listeners:
	public:
		IPs:
			- 0.0.0.0
		SMTP:
			Enabled: true
			Port: 25
			RequireSTARTTLS: true
		Submission:
			Enabled: true
			Port: 587
			NoRequireSTARTTLS: false
		IMAP:
			Enabled: false
		IMAPS:
			Enabled: false
		TLS:
			ACME: letsencrypt

AdminHTTPS:
	Enabled: false
AdminHTTP:
	Enabled: true
	Port: 8080
