/*
 * <auto-generated />
 * This file is auto-generated from core/models/src/icons/svg by core/models/scripts/generate-icons.cjs.
 * Do not edit this file directly. Run 'node core/models/scripts/generate-icons.cjs' to regenerate.
 */

/**
 * The built-in logos a user can pick for an item, keyed by the Source a builtin logo row stores.
 * Single source of truth for all built-in logos across platforms.
 */
export const BuiltinLogoSvgs = {
  'shopping': `<svg viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M11 12.5V9C11 6.24 13.24 4 16 4C18.76 4 21 6.24 21 9V12.5" stroke="#d68338" stroke-width="2.5" stroke-linecap="round"/>
  <path d="M6.3 10H25.7L27.2 26.2C27.31 27.37 26.39 28.4 25.21 28.4H6.79C5.61 28.4 4.69 27.37 4.8 26.2L6.3 10Z" fill="#f49541"/>
  <circle cx="11" cy="14" r="1.5" fill="#ffe096"/>
  <circle cx="21" cy="14" r="1.5" fill="#ffe096"/>
</svg>`,

  'bank': `<svg viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M16 4L29 11H3L16 4Z" fill="#f49541"/>
  <rect x="6" y="13" width="3" height="11" fill="#f49541"/>
  <rect x="14.5" y="13" width="3" height="11" fill="#f49541"/>
  <rect x="23" y="13" width="3" height="11" fill="#f49541"/>
  <rect x="3" y="25" width="26" height="3" rx="1" fill="#d68338"/>
</svg>`,

  'mail': `<svg viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
  <rect x="3" y="7" width="26" height="18" rx="3" fill="#f49541"/>
  <path d="M4 10L16 18L28 10" stroke="#ffe096" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/>
</svg>`,

  'social': `<svg viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
  <circle cx="22" cy="11" r="4" fill="#d68338"/>
  <path d="M18 27C18 21.5 20.5 18.5 23.5 18.5C26.5 18.5 29.5 21 29.5 27H18Z" fill="#d68338"/>
  <circle cx="12" cy="11" r="5" fill="#f49541"/>
  <path d="M2.5 27C2.5 21.5 6.5 18 12 18C17.5 18 21.5 21.5 21.5 27H2.5Z" fill="#f49541"/>
</svg>`,

  'work': `<svg viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M12 8V6C12 5 12.9 4 14 4H18C19.1 4 20 5 20 6V8" stroke="#d68338" stroke-width="2.5" stroke-linecap="round"/>
  <rect x="3" y="8" width="26" height="18" rx="3" fill="#f49541"/>
  <rect x="3" y="15" width="26" height="2.5" fill="#d68338"/>
  <rect x="13.5" y="14" width="5" height="5" rx="1" fill="#ffe096"/>
</svg>`,

  'game': `<svg viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
  <rect x="2" y="7" width="28" height="18" rx="9" fill="#f49541"/>
  <rect x="7" y="15" width="7" height="2.2" rx="1.1" fill="#ffe096"/>
  <rect x="9.4" y="12.6" width="2.2" height="7" rx="1.1" fill="#ffe096"/>
  <circle cx="21" cy="14" r="1.9" fill="#ffe096"/>
  <circle cx="24.5" cy="18" r="1.9" fill="#ffe096"/>
</svg>`,

  'media': `<svg viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
  <rect x="3" y="5" width="26" height="22" rx="4" fill="#f49541"/>
  <path d="M13 11.5L21 16L13 20.5V11.5Z" fill="#ffe096"/>
</svg>`,

  'travel': `<svg viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M14 12.4L2 19V22L14 18.5V12.4ZM18 12.4L30 19V22L18 18.5V12.4Z" fill="#d68338"/>
  <path d="M14 23.5L11 26V28.5L16 27L21 28.5V26L18 23.5H14Z" fill="#d68338"/>
  <path d="M16 3C17.1 3 18 3.9 18 5V24C18 25.5 17.1 27 16 27C14.9 27 14 25.5 14 24V5C14 3.9 14.9 3 16 3Z" fill="#f49541"/>
</svg>`,

  'health': `<svg viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M16 27C16 27 3 19.5 3 11.5C3 7.4 6.1 4.5 9.8 4.5C12.2 4.5 14.5 5.9 16 8C17.5 5.9 19.8 4.5 22.2 4.5C25.9 4.5 29 7.4 29 11.5C29 19.5 16 27 16 27Z" fill="#f49541"/>
  <path d="M14.5 11H17.5V14H20.5V17H17.5V20H14.5V17H11.5V14H14.5V11Z" fill="#ffe096"/>
</svg>`,

  'dev': `<svg viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
  <rect x="2" y="5" width="28" height="22" rx="4" fill="#f49541"/>
  <path d="M12 12L8 16.5L12 21" stroke="#ffe096" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/>
  <path d="M20 12L24 16.5L20 21" stroke="#ffe096" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/>
</svg>`,
} as const;

export type BuiltinLogoKey = keyof typeof BuiltinLogoSvgs;

/**
 * Get the SVG string for a built-in logo key, or null when the key is unknown to this client
 * (a newer version may have added it). Callers fall back to their placeholder icon.
 */
export function getBuiltinLogoSvg(key: string): string | null {
  return Object.prototype.hasOwnProperty.call(BuiltinLogoSvgs, key) ? BuiltinLogoSvgs[key as BuiltinLogoKey] : null;
}

/**
 * Get all built-in logo keys, in the order they are offered to the user.
 */
export function getAllBuiltinLogoKeys(): BuiltinLogoKey[] {
  return Object.keys(BuiltinLogoSvgs) as BuiltinLogoKey[];
}
