// <auto-generated />
// This file is auto-generated from core/models/scripts/generate-key-vocabulary.cjs.
// Do not edit this file directly. Run 'core/models/build.sh' (or 'node core/models/scripts/generate-key-vocabulary.cjs') to regenerate.

package net.aliasvault.app.vaultstore.models

/**
 * Unlock methods a user can enroll. Each enrolled method stores one copy of the user's Account Key,
 * encrypted with a KEK derived from that method's secret.
 */
object UnlockMethodType {
    /**
     * Master password: the KEK is derived from the password via Argon2.
     */
    const val PASSWORD = "password"

    /**
     * All known UnlockMethodType tokens.
     */
    val all = listOf(PASSWORD)
}
