// <auto-generated />
// This file is auto-generated from core/models/scripts/generate-key-vocabulary.cjs.
// Do not edit this file directly. Run 'core/models/build.sh' (or 'node core/models/scripts/generate-key-vocabulary.cjs') to regenerate.

package net.aliasvault.app.vaultstore.models

/**
 * The algorithms a piece of vault key ciphertext can be encrypted with. The token travels next to every
 * ciphertext, so a reader always knows how to open it without inferring anything from context.
 */
object VaultKeyAlgorithm {
    /**
     * AES-256-GCM: symmetric, used where the reader already holds the wrapping key.
     */
    const val AES256_GCM = "aes256-gcm"

    /**
     * RSA-OAEP with SHA-256: asymmetric, used to encrypt a VEK to a recipient's public key.
     */
    const val RSA_OAEP_SHA256 = "rsa-oaep-sha256"

    /**
     * All known VaultKeyAlgorithm tokens.
     */
    val all = listOf(AES256_GCM, RSA_OAEP_SHA256)
}
