// <auto-generated />
// This file is auto-generated from core/rust/src/vault_codec/types.rs (BUCKET_TABLES).
// Do not edit this file directly. Run 'core/models/build.sh' (or 'node core/models/scripts/generate-bucket-categories.cjs') to regenerate.

package net.aliasvault.app.vaultstore.models

/**
 * Known data-bucket categories for the manifest-v1 storage format.
 * The canonical list lives in the Rust codec's BUCKET_TABLES.
 */
object VaultDataBucketCategory {
    /**
     * User client settings (sort order, autofill prefs, identity defaults, etc.).
     */
    const val SETTINGS = "Settings"

    /**
     * All known data bucket categories.
     */
    val all = listOf(SETTINGS)
}
