// <auto-generated />
// This file is auto-generated from core/models/src/vault/VaultTableRegistry.ts (VAULT_BUCKET_CATEGORIES).
// Do not edit this file directly. Run 'core/models/build.sh' (or 'node core/models/scripts/generate-vault-table-registry.cjs') to regenerate.

namespace AliasVault.Shared.Models.WebApi.V2.Vault;

using System.Text.Json.Serialization;

/// <summary>
/// Known data-bucket categories for the manifest-v1 storage format. Each value is one small, independently-versioned,
/// user-scoped category of encrypted data kept out of the main vault content manifest so it syncs cheaply.
/// Serialized as its string name on the wire (not the numeric value) and stored as a string in the database.
/// Adding a new kind requires a server-side rollout first, because the server reasons about kinds for
/// per-kind retention policies. The canonical list lives in the vault table registry (core/models).
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum VaultDataBucketCategory
{
    /// <summary>User client settings (sort order, autofill prefs, identity defaults, etc.).</summary>
    Settings = 0,

    /// <summary>Per-item usage statistics (last used, use counts).</summary>
    Stats = 1,
}
