translation_memory:
  tm_id: auto
quality_assurance:
  - inconsistent_translations
  - empty_translations
  - duplicate_translations
workflow_id: auto
export_settings:
  - pattern: '**/*.json'
    format: json
    escape_quotes: 0
  - pattern: '**/*.resx'
    format: resx
  - pattern: '**/*.strings'
    format: strings
  - pattern: '**/*.xml'
    format: android
notifications:
  - event: translation_request
    user_role: translator
  - event: translation_completed
    user_role: manager
pull_request:
  title: Update translations from Crowdin
  body: This PR contains updated translations from Crowdin. Please review and merge if everything looks correct.
languages:
  - nl
  - de
  - fr
  - es
  - it
  - pt
  - uk
  - zh
  - ja
  - ko
base_path: ./
preserve_hierarchy: 1
files:
  - source: /apps/server/AliasVault.Client/wwwroot/locales/en.json
    translation: /apps/server/AliasVault.Client/wwwroot/locales/%two_letters_code%.json
    type: json
  - source: /apps/server/AliasVault.Client/Resources/**/*.en.resx
    translation: /%original_path%/%file_name%.%two_letters_code%.resx
    type: resx
    translation_replace:
      .en: ''
  - source: /apps/browser-extension/src/locales/en.json
    translation: /apps/browser-extension/src/locales/%two_letters_code%.json
    type: json
  - source: /apps/mobile-app/i18n/locales/en.json
    translation: /apps/mobile-app/i18n/locales/%two_letters_code%.json
    type: json
  - source: /apps/mobile-app/ios/AliasVault/en.lproj/Localizable.strings
    translation: /apps/mobile-app/ios/AliasVault/%two_letters_code%.lproj/Localizable.strings
    type: strings
  - source: /apps/mobile-app/ios/AliasVault/en.lproj/InfoPlist.strings
    translation: /apps/mobile-app/ios/AliasVault/%two_letters_code%.lproj/InfoPlist.strings
    type: strings
  - source: /apps/mobile-app/ios/Autofill/en.lproj/Localizable.strings
    translation: /apps/mobile-app/ios/Autofill/%two_letters_code%.lproj/Localizable.strings
    type: strings
  - source: /apps/mobile-app/ios/VaultUI/en.lproj/Localizable.strings
    translation: /apps/mobile-app/ios/VaultUI/%two_letters_code%.lproj/Localizable.strings
    type: strings
  - source: /apps/mobile-app/android/app/src/main/res/values/strings.xml
    translation: /apps/mobile-app/android/app/src/main/res/values-%two_letters_code%/strings.xml
    type: android
commit_message: 'Update translations from Crowdin [ci skip]'
