translation_memory:
  tm_id: auto
quality_assurance:
  - inconsistent_translations
  - empty_translations
  - duplicate_translations
workflow_id: auto
export_settings:
  - pattern: '**/*.json'
    format: json
    escape_quotes: 0
  - pattern: '**/*.resx'
    format: resx
  - pattern: '**/*.strings'
    format: strings
  - pattern: '**/*.xml'
    format: android
notifications:
  - event: translation_request
    user_role: translator
  - event: translation_completed
    user_role: manager
pull_request:
  title: Update translations from Crowdin
  body: This PR contains updated translations from Crowdin. Please review and merge if everything looks correct.
base_path: ./
preserve_hierarchy: 1
files:
  - source: /core/i18n/locales/en.json
    translation: /core/i18n/locales/%two_letters_code%.json
    type: json
commit_message: 'Update translations from Crowdin [ci skip]'
