// <auto-generated />
// This file is auto-generated from core/models/src/icons/svg by core/models/scripts/generate-icons.cjs.
// Do not edit this file directly. Run 'node core/models/scripts/generate-icons.cjs' to regenerate.

import React from 'react';
import Svg, { Circle, Path, Rect } from 'react-native-svg';

export const ShoppingIcon = ({ width = 32, height = 32 }: { width?: number; height?: number }): React.ReactElement => (
  <Svg width={width} height={height} viewBox="0 0 32 32" fill="none">
    <Path d="M11 12.5V9C11 6.24 13.24 4 16 4C18.76 4 21 6.24 21 9V12.5" stroke="#d68338" strokeWidth="2.5" strokeLinecap="round" />
    <Path d="M6.3 10H25.7L27.2 26.2C27.31 27.37 26.39 28.4 25.21 28.4H6.79C5.61 28.4 4.69 27.37 4.8 26.2L6.3 10Z" fill="#f49541" />
    <Circle cx="11" cy="14" r="1.5" fill="#ffe096" />
    <Circle cx="21" cy="14" r="1.5" fill="#ffe096" />
  </Svg>
);

export const BankIcon = ({ width = 32, height = 32 }: { width?: number; height?: number }): React.ReactElement => (
  <Svg width={width} height={height} viewBox="0 0 32 32" fill="none">
    <Path d="M16 4L29 11H3L16 4Z" fill="#f49541" />
    <Rect x="6" y="13" width="3" height="11" fill="#f49541" />
    <Rect x="14.5" y="13" width="3" height="11" fill="#f49541" />
    <Rect x="23" y="13" width="3" height="11" fill="#f49541" />
    <Rect x="3" y="25" width="26" height="3" rx="1" fill="#d68338" />
  </Svg>
);

export const MailIcon = ({ width = 32, height = 32 }: { width?: number; height?: number }): React.ReactElement => (
  <Svg width={width} height={height} viewBox="0 0 32 32" fill="none">
    <Rect x="3" y="7" width="26" height="18" rx="3" fill="#f49541" />
    <Path d="M4 10L16 18L28 10" stroke="#ffe096" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" />
  </Svg>
);

export const SocialIcon = ({ width = 32, height = 32 }: { width?: number; height?: number }): React.ReactElement => (
  <Svg width={width} height={height} viewBox="0 0 32 32" fill="none">
    <Circle cx="22" cy="11" r="4" fill="#d68338" />
    <Path d="M18 27C18 21.5 20.5 18.5 23.5 18.5C26.5 18.5 29.5 21 29.5 27H18Z" fill="#d68338" />
    <Circle cx="12" cy="11" r="5" fill="#f49541" />
    <Path d="M2.5 27C2.5 21.5 6.5 18 12 18C17.5 18 21.5 21.5 21.5 27H2.5Z" fill="#f49541" />
  </Svg>
);

export const WorkIcon = ({ width = 32, height = 32 }: { width?: number; height?: number }): React.ReactElement => (
  <Svg width={width} height={height} viewBox="0 0 32 32" fill="none">
    <Path d="M12 8V6C12 5 12.9 4 14 4H18C19.1 4 20 5 20 6V8" stroke="#d68338" strokeWidth="2.5" strokeLinecap="round" />
    <Rect x="3" y="8" width="26" height="18" rx="3" fill="#f49541" />
    <Rect x="3" y="15" width="26" height="2.5" fill="#d68338" />
    <Rect x="13.5" y="14" width="5" height="5" rx="1" fill="#ffe096" />
  </Svg>
);

export const GameIcon = ({ width = 32, height = 32 }: { width?: number; height?: number }): React.ReactElement => (
  <Svg width={width} height={height} viewBox="0 0 32 32" fill="none">
    <Rect x="2" y="7" width="28" height="18" rx="9" fill="#f49541" />
    <Rect x="7" y="15" width="7" height="2.2" rx="1.1" fill="#ffe096" />
    <Rect x="9.4" y="12.6" width="2.2" height="7" rx="1.1" fill="#ffe096" />
    <Circle cx="21" cy="14" r="1.9" fill="#ffe096" />
    <Circle cx="24.5" cy="18" r="1.9" fill="#ffe096" />
  </Svg>
);

export const MediaIcon = ({ width = 32, height = 32 }: { width?: number; height?: number }): React.ReactElement => (
  <Svg width={width} height={height} viewBox="0 0 32 32" fill="none">
    <Rect x="3" y="5" width="26" height="22" rx="4" fill="#f49541" />
    <Path d="M13 11.5L21 16L13 20.5V11.5Z" fill="#ffe096" />
  </Svg>
);

export const TravelIcon = ({ width = 32, height = 32 }: { width?: number; height?: number }): React.ReactElement => (
  <Svg width={width} height={height} viewBox="0 0 32 32" fill="none">
    <Path d="M14 12.4L2 19V22L14 18.5V12.4ZM18 12.4L30 19V22L18 18.5V12.4Z" fill="#d68338" />
    <Path d="M14 23.5L11 26V28.5L16 27L21 28.5V26L18 23.5H14Z" fill="#d68338" />
    <Path d="M16 3C17.1 3 18 3.9 18 5V24C18 25.5 17.1 27 16 27C14.9 27 14 25.5 14 24V5C14 3.9 14.9 3 16 3Z" fill="#f49541" />
  </Svg>
);

export const HealthIcon = ({ width = 32, height = 32 }: { width?: number; height?: number }): React.ReactElement => (
  <Svg width={width} height={height} viewBox="0 0 32 32" fill="none">
    <Path d="M16 27C16 27 3 19.5 3 11.5C3 7.4 6.1 4.5 9.8 4.5C12.2 4.5 14.5 5.9 16 8C17.5 5.9 19.8 4.5 22.2 4.5C25.9 4.5 29 7.4 29 11.5C29 19.5 16 27 16 27Z" fill="#f49541" />
    <Path d="M14.5 11H17.5V14H20.5V17H17.5V20H14.5V17H11.5V14H14.5V11Z" fill="#ffe096" />
  </Svg>
);

export const DevIcon = ({ width = 32, height = 32 }: { width?: number; height?: number }): React.ReactElement => (
  <Svg width={width} height={height} viewBox="0 0 32 32" fill="none">
    <Rect x="2" y="5" width="28" height="22" rx="4" fill="#f49541" />
    <Path d="M12 12L8 16.5L12 21" stroke="#ffe096" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" />
    <Path d="M20 12L24 16.5L20 21" stroke="#ffe096" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" />
  </Svg>
);

/**
 * Map of icon key to React Native SVG component.
 */
export const builtinLogoComponents = {
  'shopping': ShoppingIcon,
  'bank': BankIcon,
  'mail': MailIcon,
  'social': SocialIcon,
  'work': WorkIcon,
  'game': GameIcon,
  'media': MediaIcon,
  'travel': TravelIcon,
  'health': HealthIcon,
  'dev': DevIcon,
};

export type BuiltinLogoComponentKey = keyof typeof builtinLogoComponents;
