// <auto-generated />
// This file is auto-generated from core/models/src/icons/svg by core/models/scripts/generate-icons.cjs.
// Do not edit this file directly. Run 'node core/models/scripts/generate-icons.cjs' to regenerate.

import React from 'react';
import Svg, { Circle, Path, Rect } from 'react-native-svg';

export const PlaceholderIcon = ({ width = 32, height = 32 }: { width?: number; height?: number }): React.ReactElement => (
  <Svg width={width} height={height} viewBox="0 0 32 32" fill="none">
    <Circle cx="10" cy="10" r="6.5" fill="none" stroke="#f49541" strokeWidth="2.5" />
    <Circle cx="10" cy="10" r="2.5" fill="none" stroke="#f49541" strokeWidth="2" />
    <Path d="M15 15L27 27" stroke="#f49541" strokeWidth="2.5" strokeLinecap="round" />
    <Path d="M19 19L23 15" stroke="#f49541" strokeWidth="2.5" strokeLinecap="round" />
    <Path d="M24 24L28 20" stroke="#f49541" strokeWidth="2.5" strokeLinecap="round" />
  </Svg>
);

export const NoteIcon = ({ width = 32, height = 32 }: { width?: number; height?: number }): React.ReactElement => (
  <Svg width={width} height={height} viewBox="0 0 32 32" fill="none">
    <Path d="M8 4C6.9 4 6 4.9 6 6V26C6 27.1 6.9 28 8 28H24C25.1 28 26 27.1 26 26V11L19 4H8Z" fill="#f49541" />
    <Path d="M19 4V11H26L19 4Z" fill="#d68338" />
    <Rect x="10" y="14" width="12" height="1.5" rx="0.75" fill="#ffe096" />
    <Rect x="10" y="18" width="10" height="1.5" rx="0.75" fill="#ffe096" />
    <Rect x="10" y="22" width="8" height="1.5" rx="0.75" fill="#ffe096" />
  </Svg>
);

export const CreditCardIcon = ({ width = 32, height = 32 }: { width?: number; height?: number }): React.ReactElement => (
  <Svg width={width} height={height} viewBox="0 0 32 32" fill="none">
    <Rect x="2" y="6" width="28" height="20" rx="3" fill="#f49541" />
    <Rect x="2" y="11" width="28" height="4" fill="#d68338" />
    <Rect x="5" y="18" width="8" height="2" rx="1" fill="#ffe096" />
    <Rect x="5" y="22" width="5" height="1.5" rx="0.75" fill="#fbcb74" />
  </Svg>
);

export const VisaIcon = ({ width = 32, height = 32 }: { width?: number; height?: number }): React.ReactElement => (
  <Svg width={width} height={height} viewBox="0 0 32 32" fill="none">
    <Rect x="2" y="6" width="28" height="20" rx="3" fill="#f49541" />
    <Path d="M7 13L9 19L11 13M13.2 13V19M18.6 13.7C18.1 13.2 17.4 13 16.7 13C15.7 13 15 13.6 15 14.4C15 16.2 18.8 15.8 18.8 17.6C18.8 18.4 18 19 17 19C16.2 19 15.4 18.7 14.9 18.2M20.5 19L22.75 13L25 19M21.3 17H24.2" stroke="#ffe096" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" />
  </Svg>
);

export const MastercardIcon = ({ width = 32, height = 32 }: { width?: number; height?: number }): React.ReactElement => (
  <Svg width={width} height={height} viewBox="0 0 32 32" fill="none">
    <Rect x="2" y="6" width="28" height="20" rx="3" fill="#f49541" />
    <Path d="M16 11.75C17.35 12.76 18.2 14.28 18.2 16C18.2 17.72 17.35 19.24 16 20.25C14.65 19.24 13.8 17.72 13.8 16C13.8 14.28 14.65 12.76 16 11.75Z" fill="#fbcb74" />
    <Circle cx="12.5" cy="16" r="5" stroke="#ffe096" strokeWidth="1.6" />
    <Circle cx="19.5" cy="16" r="5" stroke="#ffe096" strokeWidth="1.6" />
  </Svg>
);

export const AmexIcon = ({ width = 32, height = 32 }: { width?: number; height?: number }): React.ReactElement => (
  <Svg width={width} height={height} viewBox="0 0 32 32" fill="none">
    <Rect x="2" y="6" width="28" height="20" rx="3" fill="#f49541" />
    <Path d="M7 19L8.8 13L10.6 19M7.6 17H10M12 19V13L13.8 16.5L15.6 13V19M20.4 13H17.4V19H20.4M17.4 16H19.8M22 13L25.2 19M25.2 13L22 19" stroke="#ffe096" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
  </Svg>
);

export const DiscoverIcon = ({ width = 32, height = 32 }: { width?: number; height?: number }): React.ReactElement => (
  <Svg width={width} height={height} viewBox="0 0 32 32" fill="none">
    <Rect x="2" y="6" width="28" height="20" rx="3" fill="#f49541" />
    <Path d="M6 13.5V18.5H7.2C8.6 18.5 9.5 17.5 9.5 16C9.5 14.5 8.6 13.5 7.2 13.5H6ZM11.4 13.5V18.5M15.5 14C15.1 13.7 14.6 13.5 14.1 13.5C13.4 13.5 12.9 13.9 12.9 14.5C12.9 15.8 15.7 15.4 15.7 16.9C15.7 17.5 15.1 18.5 14.1 18.5C13.6 18.5 13.1 18.3 12.7 18" stroke="#ffe096" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" />
    <Circle cx="22" cy="16" r="4" fill="#ffe096" />
  </Svg>
);

/**
 * Map of icon key to React Native SVG component.
 */
export const itemTypeIconComponents = {
  'placeholder': PlaceholderIcon,
  'note': NoteIcon,
  'credit-card': CreditCardIcon,
  'visa': VisaIcon,
  'mastercard': MastercardIcon,
  'amex': AmexIcon,
  'discover': DiscoverIcon,
};

export type ItemTypeIconComponentKey = keyof typeof itemTypeIconComponents;
