project_id: "aliasvault-mobile"
api_token_env: "CROWDIN_API_TOKEN"
base_path: "."
base_url: "https://api.crowdin.com"

preserve_hierarchy: true

files:
  # React Native JSON translation files
  - source: "i18n/locales/en.json"
    translation: "i18n/locales/%two_letters_code%.json"
    type: "json"
    
  # iOS native localization files
  - source: "ios/AliasVault/en.lproj/Localizable.strings"
    translation: "ios/AliasVault/%two_letters_code%.lproj/Localizable.strings"
    type: "strings"
    
  # Android native localization files (if needed in the future)
  - source: "android/app/src/main/res/values/strings.xml"
    translation: "android/app/src/main/res/values-%two_letters_code%/strings.xml"
    type: "android"
    ignore:
      - "android/app/src/main/res/values-*/**"