package net.aliasvault.app.utils

/**
 * Time-based One-Time Password (TOTP) codes, generated by the Rust core (`core/rust/src/totp`).
 * Other platform implementations: TotpUtility.ts (core/client), TotpUtility.swift (iOS).
 */
object TotpUtility {
    private const val DEFAULT_PERIOD = 30
    private const val DEFAULT_DIGITS = 6
    private const val DEFAULT_ALGORITHM = "SHA1"

    /**
     * Generate the TOTP code for a Base32-encoded secret.
     * Returns null when the secret is unusable.
     */
    fun generateTotpCode(
        secret: String,
        timeSeconds: Long = System.currentTimeMillis() / 1000L,
        period: Int = DEFAULT_PERIOD,
        digits: Int = DEFAULT_DIGITS,
        algorithm: String = DEFAULT_ALGORITHM,
    ): String? = uniffi.aliasvault_core.generateTotpCode(secret, timeSeconds, algorithm, digits.coerceAtLeast(0).toUInt(), period.coerceAtLeast(0).toUInt())
}
