// <auto-generated>
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AliasServerDb.Migrations
{
    /// <summary>
    /// Swap manifest key type values for clarity.
    /// </summary>
    public partial class SwapManifestKeyTypeValues : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""UPDATE "VaultManifestAccessKeys" SET "Type" = CASE "Type" WHEN 1 THEN 2 WHEN 2 THEN 1 ELSE "Type" END WHERE "Type" IN (1, 2);""");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""UPDATE "VaultManifestAccessKeys" SET "Type" = CASE "Type" WHEN 1 THEN 2 WHEN 2 THEN 1 ELSE "Type" END WHERE "Type" IN (1, 2);""");
        }
    }
}
