// <auto-generated>
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AliasServerDb.Migrations
{
    /// <summary>
    /// Rename table names for clarity.
    /// </summary>
    public partial class DescriptiveKeyTableNames : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameTable(name: "EncryptionKeys", newName: "VaultManifestDeliveryKeys");
            migrationBuilder.RenameTable(name: "VaultKeys", newName: "VaultManifestAccessKeys");
            migrationBuilder.RenameTable(name: "UserKeys", newName: "UserGrantKeys");

            migrationBuilder.RenameColumn(name: "UserKeyId", table: "VaultManifestAccessKeys", newName: "UserGrantKeyId");

            migrationBuilder.RenameIndex(name: "IX_EncryptionKeys_VaultManifestId_IsPrimary", table: "VaultManifestDeliveryKeys", newName: "IX_VaultManifestDeliveryKeys_VaultManifestId_IsPrimary");
            migrationBuilder.RenameIndex(name: "UX_EncryptionKeys_Manifest_Primary", table: "VaultManifestDeliveryKeys", newName: "UX_VaultManifestDeliveryKeys_Manifest_Primary");
            migrationBuilder.RenameIndex(name: "IX_VaultKeys_UserKeyId", table: "VaultManifestAccessKeys", newName: "IX_VaultManifestAccessKeys_UserGrantKeyId");
            migrationBuilder.RenameIndex(name: "IX_VaultKeys_VaultManifestId", table: "VaultManifestAccessKeys", newName: "IX_VaultManifestAccessKeys_VaultManifestId");
            migrationBuilder.RenameIndex(name: "UX_VaultKeys_UserId_Type_Manifest", table: "VaultManifestAccessKeys", newName: "UX_VaultManifestAccessKeys_UserId_Type_Manifest");
            migrationBuilder.RenameIndex(name: "UX_UserKeys_User_Primary", table: "UserGrantKeys", newName: "UX_UserGrantKeys_User_Primary");

            // Postgres does not rename constraints with their table; realign PK/FK names with what EF derives.
            migrationBuilder.Sql("""ALTER TABLE "VaultManifestDeliveryKeys" RENAME CONSTRAINT "PK_EncryptionKeys" TO "PK_VaultManifestDeliveryKeys";""");
            migrationBuilder.Sql("""ALTER TABLE "VaultManifestDeliveryKeys" RENAME CONSTRAINT "FK_EncryptionKeys_VaultManifests_VaultManifestId" TO "FK_VaultManifestDeliveryKeys_VaultManifests_VaultManifestId";""");
            migrationBuilder.Sql("""ALTER TABLE "Emails" RENAME CONSTRAINT "FK_Emails_EncryptionKeys_EncryptionKeyId" TO "FK_Emails_VaultManifestDeliveryKeys_EncryptionKeyId";""");
            migrationBuilder.Sql("""ALTER TABLE "VaultManifestAccessKeys" RENAME CONSTRAINT "PK_VaultKeys" TO "PK_VaultManifestAccessKeys";""");
            migrationBuilder.Sql("""ALTER TABLE "VaultManifestAccessKeys" RENAME CONSTRAINT "FK_VaultKeys_AliasVaultUsers_UserId" TO "FK_VaultManifestAccessKeys_AliasVaultUsers_UserId";""");
            migrationBuilder.Sql("""ALTER TABLE "VaultManifestAccessKeys" RENAME CONSTRAINT "FK_VaultKeys_UserKeys_UserKeyId" TO "FK_VaultManifestAccessKeys_UserGrantKeys_UserGrantKeyId";""");
            migrationBuilder.Sql("""ALTER TABLE "UserGrantKeys" RENAME CONSTRAINT "PK_UserKeys" TO "PK_UserGrantKeys";""");
            migrationBuilder.Sql("""ALTER TABLE "UserGrantKeys" RENAME CONSTRAINT "FK_UserKeys_AliasVaultUsers_UserId" TO "FK_UserGrantKeys_AliasVaultUsers_UserId";""");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""ALTER TABLE "UserGrantKeys" RENAME CONSTRAINT "FK_UserGrantKeys_AliasVaultUsers_UserId" TO "FK_UserKeys_AliasVaultUsers_UserId";""");
            migrationBuilder.Sql("""ALTER TABLE "UserGrantKeys" RENAME CONSTRAINT "PK_UserGrantKeys" TO "PK_UserKeys";""");
            migrationBuilder.Sql("""ALTER TABLE "VaultManifestAccessKeys" RENAME CONSTRAINT "FK_VaultManifestAccessKeys_UserGrantKeys_UserGrantKeyId" TO "FK_VaultKeys_UserKeys_UserKeyId";""");
            migrationBuilder.Sql("""ALTER TABLE "VaultManifestAccessKeys" RENAME CONSTRAINT "FK_VaultManifestAccessKeys_AliasVaultUsers_UserId" TO "FK_VaultKeys_AliasVaultUsers_UserId";""");
            migrationBuilder.Sql("""ALTER TABLE "VaultManifestAccessKeys" RENAME CONSTRAINT "PK_VaultManifestAccessKeys" TO "PK_VaultKeys";""");
            migrationBuilder.Sql("""ALTER TABLE "Emails" RENAME CONSTRAINT "FK_Emails_VaultManifestDeliveryKeys_EncryptionKeyId" TO "FK_Emails_EncryptionKeys_EncryptionKeyId";""");
            migrationBuilder.Sql("""ALTER TABLE "VaultManifestDeliveryKeys" RENAME CONSTRAINT "FK_VaultManifestDeliveryKeys_VaultManifests_VaultManifestId" TO "FK_EncryptionKeys_VaultManifests_VaultManifestId";""");
            migrationBuilder.Sql("""ALTER TABLE "VaultManifestDeliveryKeys" RENAME CONSTRAINT "PK_VaultManifestDeliveryKeys" TO "PK_EncryptionKeys";""");

            migrationBuilder.RenameIndex(name: "UX_UserGrantKeys_User_Primary", table: "UserGrantKeys", newName: "UX_UserKeys_User_Primary");
            migrationBuilder.RenameIndex(name: "UX_VaultManifestAccessKeys_UserId_Type_Manifest", table: "VaultManifestAccessKeys", newName: "UX_VaultKeys_UserId_Type_Manifest");
            migrationBuilder.RenameIndex(name: "IX_VaultManifestAccessKeys_VaultManifestId", table: "VaultManifestAccessKeys", newName: "IX_VaultKeys_VaultManifestId");
            migrationBuilder.RenameIndex(name: "IX_VaultManifestAccessKeys_UserGrantKeyId", table: "VaultManifestAccessKeys", newName: "IX_VaultKeys_UserKeyId");
            migrationBuilder.RenameIndex(name: "UX_VaultManifestDeliveryKeys_Manifest_Primary", table: "VaultManifestDeliveryKeys", newName: "UX_EncryptionKeys_Manifest_Primary");
            migrationBuilder.RenameIndex(name: "IX_VaultManifestDeliveryKeys_VaultManifestId_IsPrimary", table: "VaultManifestDeliveryKeys", newName: "IX_EncryptionKeys_VaultManifestId_IsPrimary");

            migrationBuilder.RenameColumn(name: "UserGrantKeyId", table: "VaultManifestAccessKeys", newName: "UserKeyId");

            migrationBuilder.RenameTable(name: "UserGrantKeys", newName: "UserKeys");
            migrationBuilder.RenameTable(name: "VaultManifestAccessKeys", newName: "VaultKeys");
            migrationBuilder.RenameTable(name: "VaultManifestDeliveryKeys", newName: "EncryptionKeys");
        }
    }
}
