// <auto-generated>
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AliasServerDb.Migrations
{
    /// <inheritdoc />
    public partial class AccountKeyHierarchy : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_VaultKeys_EncryptionKeys_EncryptionKeyId",
                table: "VaultKeys");

            migrationBuilder.RenameColumn(
                name: "EncryptionKeyId",
                table: "VaultKeys",
                newName: "UserKeyId");

            migrationBuilder.RenameIndex(
                name: "IX_VaultKeys_EncryptionKeyId",
                table: "VaultKeys",
                newName: "IX_VaultKeys_UserKeyId");

            migrationBuilder.CreateTable(
                name: "UserKeys",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    UserId = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: false),
                    PublicKey = table.Column<string>(type: "character varying(2000)", maxLength: 2000, nullable: false),
                    EncryptedPrivateKey = table.Column<string>(type: "character varying(4000)", maxLength: 4000, nullable: false),
                    IsPrimary = table.Column<bool>(type: "boolean", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    UpdatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_UserKeys", x => x.Id);
                    table.ForeignKey(
                        name: "FK_UserKeys_AliasVaultUsers_UserId",
                        column: x => x.UserId,
                        principalTable: "AliasVaultUsers",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "UserUnlockKeys",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    UserId = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: false),
                    Type = table.Column<int>(type: "integer", nullable: false),
                    Algorithm = table.Column<string>(type: "character varying(30)", maxLength: 30, nullable: false),
                    EncryptedAccountKey = table.Column<string>(type: "text", nullable: false),
                    Metadata = table.Column<string>(type: "jsonb", nullable: true),
                    CreatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    UpdatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    LastUsedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_UserUnlockKeys", x => x.Id);
                    table.ForeignKey(
                        name: "FK_UserUnlockKeys_AliasVaultUsers_UserId",
                        column: x => x.UserId,
                        principalTable: "AliasVaultUsers",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "UX_UserKeys_User_Primary",
                table: "UserKeys",
                column: "UserId",
                unique: true,
                filter: "\"IsPrimary\"");

            migrationBuilder.CreateIndex(
                name: "UX_UserUnlockKeys_UserId_Type",
                table: "UserUnlockKeys",
                columns: new[] { "UserId", "Type" },
                unique: true);

            // Convert pre-account-key password rows into unlock-method rows. Type 0 = Password.
            migrationBuilder.Sql("""
                INSERT INTO "UserUnlockKeys" ("Id", "UserId", "Type", "Algorithm", "EncryptedAccountKey", "Metadata", "CreatedAt", "UpdatedAt", "LastUsedAt")
                SELECT "Id", "UserId", "Type", "Algorithm", "EncryptedVek", "Metadata", "CreatedAt", "UpdatedAt", "LastUsedAt"
                FROM "VaultKeys" WHERE "Type" = 0;
                """);
            migrationBuilder.Sql("""DELETE FROM "VaultKeys" WHERE "Type" = 0;""");

            // Surviving grant rows still reference pre-rename EncryptionKey ids.
            // Clear them so the new foreign key can be created against UserKeys.
            migrationBuilder.Sql("""UPDATE "VaultKeys" SET "UserKeyId" = NULL WHERE "UserKeyId" IS NOT NULL;""");

            migrationBuilder.AddForeignKey(
                name: "FK_VaultKeys_UserKeys_UserKeyId",
                table: "VaultKeys",
                column: "UserKeyId",
                principalTable: "UserKeys",
                principalColumn: "Id",
                onDelete: ReferentialAction.SetNull);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_VaultKeys_UserKeys_UserKeyId",
                table: "VaultKeys");

            migrationBuilder.DropTable(
                name: "UserKeys");

            migrationBuilder.DropTable(
                name: "UserUnlockKeys");

            migrationBuilder.RenameColumn(
                name: "UserKeyId",
                table: "VaultKeys",
                newName: "EncryptionKeyId");

            migrationBuilder.RenameIndex(
                name: "IX_VaultKeys_UserKeyId",
                table: "VaultKeys",
                newName: "IX_VaultKeys_EncryptionKeyId");

            migrationBuilder.AddForeignKey(
                name: "FK_VaultKeys_EncryptionKeys_EncryptionKeyId",
                table: "VaultKeys",
                column: "EncryptionKeyId",
                principalTable: "EncryptionKeys",
                principalColumn: "Id",
                onDelete: ReferentialAction.SetNull);
        }
    }
}
