/**
 * <auto-generated />
 * This file is auto-generated from core/models/scripts/generate-key-vocabulary.cjs.
 * Do not edit this file directly. Run 'core/models/build.sh' (or 'node core/models/scripts/generate-key-vocabulary.cjs') to regenerate.
 */

/**
 * How one user's access to one manifest's VEK is protected. Every (user, manifest) access path is
 * exactly one of these, and the token decides where the client looks for the key that opens the manifest.
 */
export const ManifestKeyType = {
  /**
   * The VEK is encrypted with the user's own Account Key, which their unlock chain produces.
   */
  AccountKey: 'accountkey',

  /**
   * A grant: the VEK is encrypted to a public key of the user, so only its holder's private half can open it.
   */
  GrantKey: 'grantkey',
} as const;

/**
 * Type representing all valid ManifestKeyType tokens.
 */
export type ManifestKeyTypeValue = typeof ManifestKeyType[keyof typeof ManifestKeyType];
