/**
 * <auto-generated />
 * This file is auto-generated from core/models/scripts/generate-key-vocabulary.cjs.
 * Do not edit this file directly. Run 'core/models/build.sh' (or 'node core/models/scripts/generate-key-vocabulary.cjs') to regenerate.
 */

/**
 * Unlock methods a user can enroll. Each enrolled method stores one copy of the user's Account Key,
 * encrypted with a KEK derived from that method's secret.
 */
export const UnlockMethodType = {
  /**
   * Master password: Argon2id of the password gives the unlock key, which the KEK and SRP input are HKDF-derived from.
   */
  Password: 'password',
} as const;

/**
 * Type representing all valid UnlockMethodType tokens.
 */
export type UnlockMethodTypeValue = typeof UnlockMethodType[keyof typeof UnlockMethodType];
