// <auto-generated />
// This file is auto-generated from core/models/src/defaults/Languages.ts
// Do not edit this file directly. Run 'core/models/build.sh' (or
// 'node core/models/scripts/generate-languages.cjs') to regenerate.

#nullable enable

namespace AliasVault.Client.Main.Models;

/// <summary>
/// Generic language reference shared across all AliasVault clients: maps a two-letter ISO 639-1
/// code to a flag and native label.
/// </summary>
public static class Languages
{
    /// <summary>
    /// Default ISO language code used as the universal fallback.
    /// </summary>
    public const string DefaultLanguageCode = "en";

    /// <summary>
    /// Known languages keyed by ISO 639-1 code, with a flag and native label.
    /// </summary>
    private static readonly (string Code, string Flag, string Label)[] Meta =
    [
        ("en", "🇬🇧", "English"),
        ("nl", "🇳🇱", "Nederlands"),
        ("de", "🇩🇪", "Deutsch"),
        ("fr", "🇫🇷", "Français"),
        ("es", "🇪🇸", "Español"),
        ("it", "🇮🇹", "Italiano"),
        ("da", "🇩🇰", "Dansk"),
        ("fi", "🇫🇮", "Suomi"),
        ("he", "🇮🇱", "עברית"),
        ("pl", "🇵🇱", "Polski"),
        ("pt", "🇧🇷", "Português"),
        ("ro", "🇷🇴", "Română"),
        ("ru", "🇷🇺", "Русский"),
        ("sv", "🇸🇪", "Svenska"),
        ("uk", "🇺🇦", "Українська"),
        ("zh", "🇨🇳", "中文"),
    ];

    /// <summary>
    /// Normalize an app/UI language tag to a two-letter lowercase ISO code (e.g. "nl-NL" -> "nl").
    /// </summary>
    /// <param name="code">The language tag.</param>
    /// <returns>The two-letter lowercase code.</returns>
    public static string Normalize(string? code)
    {
        var value = code ?? string.Empty;
        return (value.Length >= 2 ? value.Substring(0, 2) : value).ToLowerInvariant();
    }

    /// <summary>
    /// Get the display label (flag + native name) for an ISO language code. Falls back to a globe
    /// flag and the raw code for unknown languages.
    /// </summary>
    /// <param name="code">The ISO language code (case-insensitive).</param>
    /// <returns>A display string such as "🇳🇱 Nederlands".</returns>
    public static string GetDisplayLabel(string code)
    {
        var iso = Normalize(code);
        foreach (var (metaCode, flag, label) in Meta)
        {
            if (metaCode == iso)
            {
                return $"{flag} {label}";
            }
        }

        return $"🌐 {code}";
    }

    /// <summary>
    /// Resolve a default language code for an app/UI language, restricted to a set of available
    /// codes. Returns the app language when available, otherwise the first available code,
    /// otherwise English.
    /// </summary>
    /// <param name="appLanguage">The app/UI language tag.</param>
    /// <param name="availableCodes">The codes the feature actually supports.</param>
    /// <returns>The resolved ISO code.</returns>
    public static string ResolveDefaultLanguage(string? appLanguage, System.Collections.Generic.IReadOnlyList<string> availableCodes)
    {
        var iso = Normalize(appLanguage);
        foreach (var code in availableCodes)
        {
            if (string.Equals(code, iso, System.StringComparison.OrdinalIgnoreCase))
            {
                return iso;
            }
        }

        return availableCodes.Count > 0 ? availableCodes[0] : DefaultLanguageCode;
    }
}
