/**
 * <auto-generated />
 * This file is auto-generated from core/rust/src/vault_codec/types.rs (BUCKET_TABLES).
 * Do not edit this file directly. Run 'core/models/build.sh' (or 'node core/models/scripts/generate-bucket-categories.cjs') to regenerate.
 */

/**
 * Known data-bucket categories for the manifest-v1 storage format. Each value is one small,
 * independently-versioned, user-scoped category of encrypted data kept out of the main vault content
 * manifest so it syncs cheaply. Serialized as its string name on the wire. The canonical list lives in
 * the Rust codec's BUCKET_TABLES.
 */
export const VaultDataBucketCategory = {
  /**
   * User client settings (sort order, autofill prefs, identity defaults, etc.).
   */
  Settings: 'Settings',

  /**
   * The user's asymmetric keypairs, which are used for both email decryption and to unwrap shared-folder VEKs.
   */
  EncryptionKeys: 'EncryptionKeys',
} as const;

/**
 * Type representing all valid vault data bucket category values.
 */
export type VaultDataBucketCategoryValue = typeof VaultDataBucketCategory[keyof typeof VaultDataBucketCategory];
