services:
  postgres-dev:
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    volumes:
      - ../database/postgres-dev:/var/lib/postgresql/data:rw
      - ../apps/server/Databases/AliasServerDb/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_DB=aliasvault
      - POSTGRES_USER=aliasvault
      - POSTGRES_PASSWORD=password
    restart: "no"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aliasvault"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]