// <auto-generated />
// This file is auto-generated from core/models/scripts/generate-key-vocabulary.cjs.
// Do not edit this file directly. Run 'core/models/build.sh' (or 'node core/models/scripts/generate-key-vocabulary.cjs') to regenerate.

import Foundation

/// The algorithms an account signing keypair can sign with.
public struct SigningKeyAlgorithm {
    /// Ed25519 (RFC 8032), verified strictly.
    public static let ed25519 = "ed25519"

    /// All known SigningKeyAlgorithm tokens.
    public static let all = [ed25519]
}
