// <auto-generated />
// This file is auto-generated from core/models/scripts/generate-key-vocabulary.cjs.
// Do not edit this file directly. Run 'core/models/build.sh' (or 'node core/models/scripts/generate-key-vocabulary.cjs') to regenerate.

import Foundation

/// Unlock methods a user can enroll. Each enrolled method stores one copy of the user's Account Key,
/// encrypted with a KEK derived from that method's secret.
public struct UnlockMethodType {
    /// Master password: Argon2id of the password gives the unlock key, which the KEK and SRP input are HKDF-derived from.
    public static let password = "password"

    /// All known UnlockMethodType tokens.
    public static let all = [password]
}
