// <auto-generated />
// This file is auto-generated from core/models/scripts/generate-key-vocabulary.cjs.
// Do not edit this file directly. Run 'core/models/build.sh' (or 'node core/models/scripts/generate-key-vocabulary.cjs') to regenerate.

import Foundation

/// The algorithms a piece of vault key ciphertext can be encrypted with. The token travels next to every
/// ciphertext, so a reader always knows how to open it without inferring anything from context.
public struct VaultKeyAlgorithm {
    /// AES-256-GCM: symmetric, used where the reader already holds the wrapping key.
    public static let aes256Gcm = "aes256-gcm"

    /// RSA-OAEP with SHA-256: asymmetric, used to encrypt a VEK to a recipient's public key.
    public static let rsaOaepSha256 = "rsa-oaep-sha256"

    /// All known VaultKeyAlgorithm tokens.
    public static let all = [aes256Gcm, rsaOaepSha256]
}
