// <auto-generated />
// This file is auto-generated from core/models/src/vault/VaultTableRegistry.ts (VAULT_BUCKET_CATEGORIES).
// Do not edit this file directly. Run 'core/models/build.sh' (or 'node core/models/scripts/generate-vault-table-registry.cjs') to regenerate.

import Foundation

/// Known data-bucket categories for the manifest-v1 storage format.
/// The canonical list lives in the vault table registry (core/models).
public struct VaultDataBucketCategory {
    /// User client settings (sort order, autofill prefs, identity defaults, etc.).
    public static let settings = "Settings"

    /// Per-item usage statistics (last used, use counts).
    public static let stats = "Stats"

    /// All known data bucket categories.
    public static let all = [settings, stats]
}
