// <auto-generated />
// This file is auto-generated from core/rust/src/vault_codec/types.rs (BUCKET_TABLES).
// Do not edit this file directly. Run 'core/models/build.sh' (or 'node core/models/scripts/generate-bucket-categories.cjs') to regenerate.

import Foundation

/// Known data-bucket categories for the manifest-v1 storage format.
/// The canonical list lives in the Rust codec's BUCKET_TABLES.
public struct VaultDataBucketCategory {
    /// User client settings (sort order, autofill prefs, identity defaults, etc.).
    public static let settings = "Settings"

    /// All known data bucket categories.
    public static let all = [settings]
}
