// <auto-generated />
// This file is auto-generated from core/models/src/defaults/PasswordGeneratorDefaults.ts
// Do not edit this file directly. Run 'core/models/build.sh' (or
// 'node core/models/scripts/generate-password-defaults.cjs') to regenerate.

#nullable enable

namespace AliasClientDb.Models;

/// <summary>
/// Password generator defaults shared across all AliasVault clients.
/// </summary>
public static class PasswordGeneratorDefaults
{
    /// <summary>
    /// Default length of a generated basic password.
    /// </summary>
    public const int DefaultPasswordLength = 18;

    /// <summary>
    /// Minimum password length offered by the UI length slider.
    /// </summary>
    public const int MinPasswordLength = 8;

    /// <summary>
    /// Maximum password length (also the hard cap enforced by the generator).
    /// </summary>
    public const int MaxPasswordLength = 256;

    /// <summary>
    /// Default number of words in a generated Diceware passphrase.
    /// </summary>
    public const int DefaultWordCount = 5;

    /// <summary>
    /// Minimum number of words offered by the UI word-count slider.
    /// </summary>
    public const int MinWordCount = 3;

    /// <summary>
    /// Maximum number of words (also the hard cap enforced by the generator).
    /// </summary>
    public const int MaxWordCount = 10;
}
