#!/usr/bin/env node
/**
 * Generates the AliasVault color palette for every platform.
 *
 * Input: core/models/src/colors/palette.json
 * Outputs:
 *   - core/models/src/colors/Palette.ts (TypeScript, imported as `@aliasvault/models/colors`)
 *   - core/models/src/colors/tailwind-preset.cjs (Tailwind preset for the web app, browser extension and admin)
 *   - apps/mobile-app/ios/VaultUI/ColorConstants.swift (Swift)
 *   - apps/mobile-app/android/app/src/main/res/values/av_colors.xml and values-night/av_colors.xml (Android)
 */

const fs = require('fs');
const path = require('path');

const REPO_ROOT = path.join(__dirname, '../../..');
const SOURCE_REL = 'core/models/src/colors/palette.json';
const COLORS_DIR = path.join(REPO_ROOT, 'core/models/src/colors');
const TS_OUTPUT = path.join(COLORS_DIR, 'Palette.ts');
const TAILWIND_OUTPUT = path.join(COLORS_DIR, 'tailwind-preset.cjs');
const SWIFT_OUTPUT = path.join(REPO_ROOT, 'apps/mobile-app/ios/VaultUI/ColorConstants.swift');
const ANDROID_RES = path.join(REPO_ROOT, 'apps/mobile-app/android/app/src/main/res');
const ANDROID_LIGHT_OUTPUT = path.join(ANDROID_RES, 'values/av_colors.xml');
const ANDROID_DARK_OUTPUT = path.join(ANDROID_RES, 'values-night/av_colors.xml');

const GENERATED_HEADER = `This file is auto-generated from ${SOURCE_REL} by core/models/scripts/generate-colors.cjs.`;
const REGENERATE_HINT = "Do not edit this file directly. Run 'node core/models/scripts/generate-colors.cjs' to regenerate.";

/** Opacity of the Android ripple drawn on top of a primary-colored surface. */
const ANDROID_RIPPLE_ALPHA = '33';

/** Resolve a theme value: a hex color, or a `primary.<shade>` reference into the primary scale. */
function resolveColor(palette, value, where) {
  const ref = value.match(/^primary\.(\d+)$/);
  const color = ref ? palette.primary[ref[1]] : value;
  if (!/^#[0-9a-f]{6}$/.test(color ?? '')) {
    throw new Error(`${where}: '${value}' is not a lowercase #rrggbb color or a primary.<shade> reference`);
  }
  return color;
}

/** Read the palette and resolve every theme value to a hex color. */
function readPalette() {
  const palette = JSON.parse(fs.readFileSync(path.join(REPO_ROOT, SOURCE_REL), 'utf8'));
  for (const [shade, color] of Object.entries(palette.primary)) {
    resolveColor(palette, color, `primary.${shade}`);
  }

  const lightKeys = Object.keys(palette.theme.light);
  const darkKeys = Object.keys(palette.theme.dark);
  if (lightKeys.join(',') !== darkKeys.join(',')) {
    throw new Error('theme.light and theme.dark must declare the same keys in the same order');
  }

  const theme = {};
  for (const mode of ['light', 'dark']) {
    theme[mode] = Object.fromEntries(Object.entries(palette.theme[mode]).map(([key, value]) => [key, resolveColor(palette, value, `theme.${mode}.${key}`)]));
  }
  return { primary: palette.primary, theme, keys: lightKeys };
}

/** Convert camelCase to snake_case (textMuted -> text_muted). */
function toSnakeCase(name) {
  return name.replace(/[A-Z]/g, (c) => `_${c.toLowerCase()}`);
}

/** Render an object as indented `key: 'value',` lines. */
function tsObjectLines(obj, indent) {
  return Object.entries(obj).map(([key, value]) => `${indent}${/^\d/.test(key) ? `'${key}'` : key}: '${value}',`).join('\n');
}

function generateTs({ primary, theme }) {
  return `/*
 * <auto-generated />
 * ${GENERATED_HEADER}
 * ${REGENERATE_HINT}
 */

/**
 * The AliasVault primary (brand) color scale, as used by the Tailwind \`primary-*\` classes.
 */
export const PrimaryColors = {
${tsObjectLines(primary, '  ')}
} as const;

/**
 * The semantic theme colors of the mobile apps, per color scheme.
 */
export const ThemeColors = {
  light: {
${tsObjectLines(theme.light, '    ')}
  },
  dark: {
${tsObjectLines(theme.dark, '    ')}
  },
} as const;

export type ThemeColorKey = keyof typeof ThemeColors.light;
`;
}

function generateTailwindPreset({ primary }) {
  const shades = Object.entries(primary).map(([shade, color]) => `          '${shade}': '${color}',`).join('\n');
  return `/*
 * <auto-generated />
 * ${GENERATED_HEADER}
 * ${REGENERATE_HINT}
 */

/** Tailwind preset with the AliasVault brand colors. */
module.exports = {
  theme: {
    extend: {
      colors: {
        primary: {
${shades}
        },
      },
    },
  },
};
`;
}

function generateSwift({ theme, keys }) {
  const members = (mode) => keys.map((key) => `        public static let ${key} = SwiftUI.Color(hex: "${theme[mode][key]}")`).join('\n');
  const protocolMembers = keys.map((key) => `        static var ${key}: Color { get }`).join('\n');

  return `// <auto-generated />
// ${GENERATED_HEADER}
// ${REGENERATE_HINT}

import SwiftUI

/// Color constants for the app
public struct ColorConstants {
    /// Light mode colors
    public struct Light {
${members('light')}
    }

    /// Dark mode colors
    public struct Dark {
${members('dark')}
    }

    /// Get colors for the specified color scheme
    /// - Parameter colorScheme: The current color scheme
    /// - Returns: The appropriate color constants (Light or Dark)
    public static func colors(for colorScheme: ColorScheme) -> Colors.Type {
        colorScheme == .dark ? Dark.self : Light.self
    }

    /// Protocol to enable generic access to color properties
    public protocol Colors {
${protocolMembers}
    }
}

// Conform Light and Dark to the Colors protocol
extension ColorConstants.Light: ColorConstants.Colors {}
extension ColorConstants.Dark: ColorConstants.Colors {}

// Add Color extension for hex support
extension SwiftUI.Color {
    init(hex: String) {
        let hex = hex.trimmingCharacters(in: CharacterSet.alphanumerics.inverted)
        var int: UInt64 = 0
        Scanner(string: hex).scanHexInt64(&int)
        let colorA, colorR, colorG, colorB: UInt64
        switch hex.count {
        case 3: (colorA, colorR, colorG, colorB) = (255, (int >> 8) * 17, (int >> 4 & 0xF) * 17, (int & 0xF) * 17)
        case 6: (colorA, colorR, colorG, colorB) = (255, int >> 16, int >> 8 & 0xFF, int & 0xFF)
        case 8: (colorA, colorR, colorG, colorB) = (int >> 24, int >> 16 & 0xFF, int >> 8 & 0xFF, int & 0xFF)
        default: (colorA, colorR, colorG, colorB) = (255, 0, 0, 0)
        }
        self.init(
            .sRGB,
            red: Double(colorR) / 255,
            green: Double(colorG) / 255,
            blue: Double(colorB) / 255,
            opacity: Double(colorA) / 255
        )
    }
}
`;
}

function generateAndroid({ theme, keys }, mode) {
  const colors = keys.map((key) => `  <color name="av_${toSnakeCase(key)}">${theme[mode][key]}</color>`);
  colors.push(`  <color name="av_primary_ripple">#${ANDROID_RIPPLE_ALPHA}${theme[mode].primary.slice(1)}</color>`);

  return `<?xml version="1.0" encoding="utf-8"?>
<!--
  <auto-generated />
  ${GENERATED_HEADER}
  ${REGENERATE_HINT}
-->
<resources>
${colors.join('\n')}
</resources>
`;
}

/** Write a generated file, creating its directory when missing. */
function writeFile(filePath, contents) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, contents);
  console.log(`  ✓ Generated ${path.relative(REPO_ROOT, filePath)}`);
}

function main() {
  const palette = readPalette();
  writeFile(TS_OUTPUT, generateTs(palette));
  writeFile(TAILWIND_OUTPUT, generateTailwindPreset(palette));
  writeFile(SWIFT_OUTPUT, generateSwift(palette));
  writeFile(ANDROID_LIGHT_OUTPUT, generateAndroid(palette, 'light'));
  writeFile(ANDROID_DARK_OUTPUT, generateAndroid(palette, 'dark'));
}

main();
