//! Cross-platform random identity (alias persona) generation.
//!
//! This module is the single source of truth for identity generation across AliasVault.
//! It accepts a JSON-serialized [`IdentityRequest`] and returns the generated
//! [`Identity`] as JSON, matching the JSON-in/JSON-out convention used by the other
//! core modules.
//!
//! An identity consists of a first name, last name, gender, birth date, email prefix
//! and nickname (username). Names are drawn from embedded per-language dictionaries;
//! for languages with decade-based dictionaries (de, it, ro) the first name is matched
//! to names that were popular around the generated birth year.

pub mod dictionaries;
mod username_email;

#[cfg(test)]
mod tests;

use chrono::{Datelike, Days, NaiveDate, Utc};
use rand::RngCore;
use serde::{Deserialize, Serialize};

use crate::error::VaultError;
use crate::rng::{make_rng, unbiased_index};

/// Gender value used in generated identities.
pub const GENDER_MALE: &str = "Male";
/// Gender value used in generated identities.
pub const GENDER_FEMALE: &str = "Female";

/// Default minimum age (in years) for generated birth dates.
const DEFAULT_MIN_AGE: i32 = 21;
/// Default maximum age (in years) for generated birth dates.
const DEFAULT_MAX_AGE: i32 = 65;

/// The age range option values offered by the identity generator settings UIs.
/// The first entry means "no preference" (default 21-65 age behavior).
const AGE_RANGES: &[&str] = &[
    "random", "21-25", "26-30", "31-35", "36-40", "41-45", "46-50", "51-55", "56-60", "61-65",
];

/// A generated identity. Serialized with camelCase field names to match the
/// JSON contract shared by all clients.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Identity {
    /// First name, matching the requested language and the birth decade where available.
    pub first_name: String,
    /// Last name, matching the requested language.
    pub last_name: String,
    /// Gender the first name was drawn from: "Male" or "Female".
    pub gender: String,
    /// Birth date in `yyyy-MM-dd` format.
    pub birth_date: String,
    /// Email prefix derived from the name and birth year.
    pub email_prefix: String,
    /// Username derived from the name and birth year (alphanumeric only).
    pub nick_name: String,
}

/// Explicit birth year window for generation: a target year plus/minus a deviation.
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BirthdateOptions {
    /// The central birth year.
    pub target_year: i32,
    /// Allowed deviation in years around the target (0 = within the target year only).
    pub year_deviation: i32,
}

/// Request controlling identity generation. Every field is optional so callers can
/// pass only what they need; unknown languages fall back to English.
#[derive(Debug, Clone, Default, Deserialize)]
#[serde(rename_all = "camelCase", default)]
pub struct IdentityRequest {
    /// Dictionary language code (e.g. "en", "nl"). Empty or unknown falls back to English.
    pub language: String,
    /// Gender preference: "male", "female" or "random" (default).
    pub gender: Option<String>,
    /// Age range preference as stored in settings (e.g. "21-25" or "random").
    /// Ignored when `birthdate_options` is set.
    pub age_range: Option<String>,
    /// Explicit birth year window. Takes precedence over `age_range`.
    pub birthdate_options: Option<BirthdateOptions>,
    /// Optional 32-byte RNG seed as a 64-character hex string for deterministic output
    /// (used by tests). Normal generation is non-deterministic.
    pub seed: Option<String>,
}

/// Name and birth date input for username/email prefix generation, e.g. an identity
/// previously generated by [`generate_identity`] or persona fields typed by the user.
#[derive(Debug, Clone, Default, Deserialize)]
#[serde(rename_all = "camelCase", default)]
pub struct NameInput {
    /// First name.
    pub first_name: String,
    /// Last name.
    pub last_name: String,
    /// Birth date; only the leading `yyyy` year part is used.
    pub birth_date: String,
    /// Optional 32-byte RNG seed as a 64-character hex string (used by tests).
    pub seed: Option<String>,
}

/// Generate a random identity from a JSON-serialized [`IdentityRequest`].
///
/// Returns the generated [`Identity`] as a JSON string, or a [`VaultError`] if the
/// request JSON is invalid.
pub fn generate_identity(request_json: &str) -> Result<String, VaultError> {
    let request: IdentityRequest = serde_json::from_str(request_json)?;
    let identity = generate_from_request(&request);
    Ok(serde_json::to_string(&identity)?)
}

/// Generate a random identity from an already-parsed request.
pub fn generate_from_request(request: &IdentityRequest) -> Identity {
    let mut rng = make_rng(request.seed.as_deref());
    let dictionary = dictionaries::resolve(&request.language);

    // Determine gender: explicit "male"/"female" wins, anything else is a coin flip.
    let is_male = match request.gender.as_deref() {
        Some("male") => true,
        Some("female") => false,
        _ => unbiased_index(&mut rng, 2) == 0,
    };

    // Generate the birth date first: decade-based languages select first names by birth year.
    let birthdate_options = request
        .birthdate_options
        .or_else(|| age_range_to_birthdate_options(request.age_range.as_deref().unwrap_or("")));
    let birth_date = random_birth_date(&mut rng, birthdate_options, Utc::now().date_naive());

    let first_names = select_firstnames_for_birth_year(dictionary, birth_date.year(), is_male);
    let last_names = dictionary.lastnames();

    let first_name = first_names[unbiased_index(&mut rng, first_names.len())].to_string();
    let last_name = last_names[unbiased_index(&mut rng, last_names.len())].to_string();
    let birth_year = Some(birth_date.year());

    // The email prefix and nickname are generated independently (separate random rolls).
    let email_prefix =
        username_email::generate_email_prefix(&mut rng, &first_name, &last_name, birth_year);
    let nick_name = username_email::generate_username(&mut rng, &first_name, &last_name, birth_year);

    Identity {
        first_name,
        last_name,
        gender: if is_male { GENDER_MALE } else { GENDER_FEMALE }.to_string(),
        birth_date: birth_date.format("%Y-%m-%d").to_string(),
        email_prefix,
        nick_name,
    }
}

/// Generate a username from a JSON-serialized [`NameInput`].
pub fn generate_username(input_json: &str) -> Result<String, VaultError> {
    let input: NameInput = serde_json::from_str(input_json)?;
    let mut rng = make_rng(input.seed.as_deref());
    Ok(username_email::generate_username(
        &mut rng,
        &input.first_name,
        &input.last_name,
        parse_birth_year(&input.birth_date),
    ))
}

/// Generate an email prefix from a JSON-serialized [`NameInput`].
pub fn generate_email_prefix(input_json: &str) -> Result<String, VaultError> {
    let input: NameInput = serde_json::from_str(input_json)?;
    let mut rng = make_rng(input.seed.as_deref());
    Ok(username_email::generate_email_prefix(
        &mut rng,
        &input.first_name,
        &input.last_name,
        parse_birth_year(&input.birth_date),
    ))
}

/// Generate a random alphanumeric email prefix that is not based on any identity,
/// suitable for login-type credentials without persona fields.
pub fn generate_random_email_prefix(length: u32) -> String {
    let mut rng = make_rng(None);
    username_email::generate_random_string(&mut rng, length.clamp(1, 64) as usize)
}

/// List the language codes of all bundled identity dictionaries.
pub fn available_languages() -> Vec<String> {
    dictionaries::available_codes()
        .into_iter()
        .map(|c| c.to_string())
        .collect()
}

/// List the age range option values offered by the settings UIs
/// ("random" plus 5-year ranges from 21-25 to 61-65).
pub fn available_age_ranges() -> Vec<String> {
    AGE_RANGES.iter().map(|r| r.to_string()).collect()
}

/// Convert an age range string (e.g. "21-25") to birth year options relative to the
/// current year. Returns `None` for "random", empty or malformed input, which means
/// the default age behavior (21-65) applies.
pub fn age_range_to_birthdate_options(age_range: &str) -> Option<BirthdateOptions> {
    age_range_to_birthdate_options_at(age_range, Utc::now().year())
}

/// [`age_range_to_birthdate_options`] with an explicit current year, for testability.
fn age_range_to_birthdate_options_at(age_range: &str, current_year: i32) -> Option<BirthdateOptions> {
    let (min_part, max_part) = age_range.split_once('-')?;
    let min_age: i32 = min_part.parse().ok()?;
    let max_age: i32 = max_part.parse().ok()?;

    let middle_age = (min_age + max_age).div_euclid(2);
    Some(BirthdateOptions {
        target_year: current_year - middle_age,
        year_deviation: (max_age - min_age).div_euclid(2),
    })
}

/// Generate a random birth date. With options, the date is uniform within the year
/// window; otherwise it is uniform between `today - 65 years` and `today - 21 years`.
fn random_birth_date<R: RngCore + ?Sized>(
    rng: &mut R,
    options: Option<BirthdateOptions>,
    today: NaiveDate,
) -> NaiveDate {
    let (start, end) = match options {
        Some(BirthdateOptions {
            target_year,
            year_deviation,
        }) => (
            first_day_of_year(target_year - year_deviation.abs()),
            last_day_of_year(target_year + year_deviation.abs()),
        ),
        None => (years_ago(today, DEFAULT_MAX_AGE), years_ago(today, DEFAULT_MIN_AGE)),
    };

    let days = (end - start).num_days().max(0) as usize + 1;
    start
        .checked_add_days(Days::new(unbiased_index(rng, days) as u64))
        .unwrap_or(start)
}

/// Select the first name pool for a birth year: the matching decade lists where
/// available, all decade names when the year falls outside every range, otherwise
/// the flat per-gender list.
fn select_firstnames_for_birth_year(
    dictionary: &'static dictionaries::LanguageDictionary,
    birth_year: i32,
    is_male: bool,
) -> Vec<&'static str> {
    let decades = if is_male {
        dictionary.firstnames_male_by_decade
    } else {
        dictionary.firstnames_female_by_decade
    };

    if !decades.is_empty() {
        let matching: Vec<&'static str> = decades
            .iter()
            .filter(|d| birth_year >= d.start_year && birth_year <= d.end_year)
            .flat_map(|d| d.names())
            .collect();
        if !matching.is_empty() {
            return matching;
        }

        // No decade covers this birth year: fall back to all decade names combined.
        let all: Vec<&'static str> = decades.iter().flat_map(|d| d.names()).collect();
        if !all.is_empty() {
            return all;
        }
    }

    if is_male {
        dictionary.firstnames_male()
    } else {
        dictionary.firstnames_female()
    }
}

/// Parse the leading `yyyy` year from a date string like `1990-05-15` or a full
/// ISO 8601 timestamp. Returns `None` when no valid year prefix is present.
fn parse_birth_year(birth_date: &str) -> Option<i32> {
    let digits: String = birth_date.trim().chars().take(4).collect();
    if digits.len() == 4 && digits.chars().all(|c| c.is_ascii_digit()) {
        digits.parse().ok()
    } else {
        None
    }
}

/// January 1 of the given year.
fn first_day_of_year(year: i32) -> NaiveDate {
    NaiveDate::from_ymd_opt(year, 1, 1).unwrap_or(NaiveDate::MIN)
}

/// December 31 of the given year.
fn last_day_of_year(year: i32) -> NaiveDate {
    NaiveDate::from_ymd_opt(year, 12, 31).unwrap_or(NaiveDate::MAX)
}

/// The same calendar day `years` years before `date` (Feb 29 maps to Feb 28).
fn years_ago(date: NaiveDate, years: i32) -> NaiveDate {
    date.with_year(date.year() - years)
        .unwrap_or_else(|| NaiveDate::from_ymd_opt(date.year() - years, 2, 28).unwrap_or(NaiveDate::MIN))
}
