// <auto-generated />
// This file is auto-generated from core/models/scripts/generate-key-vocabulary.cjs.
// Do not edit this file directly. Run 'core/models/build.sh' (or 'node core/models/scripts/generate-key-vocabulary.cjs') to regenerate.

#nullable enable

namespace AliasVault.Shared.Models.Enums;

/// <summary>
/// How one user's access to one manifest's VEK is protected. Every (user, manifest) access path is
/// exactly one of these, and the token decides where the client looks for the key that opens the manifest.
/// The token is the only persisted and transmitted identifier; the ordinals below are cosmetic.
/// </summary>
public enum ManifestKeyType
{
    /// <summary>
    /// The VEK is encrypted with the user's own Account Key, which their unlock chain produces.
    /// </summary>
    AccountKey = 0,

    /// <summary>
    /// A grant: the VEK is encrypted to a public key of the user, so only its holder's private half can open it.
    /// </summary>
    GrantKey = 1,
}

/// <summary>
/// Token conversions for <see cref="ManifestKeyType"/>.
/// </summary>
public static class ManifestKeyTypes
{
    /// <summary>
    /// Returns the wire/storage token for a ManifestKeyType.
    /// </summary>
    /// <param name="type">The ManifestKeyType to convert.</param>
    /// <returns>The token.</returns>
    public static string ToToken(ManifestKeyType type) => type switch
    {
        ManifestKeyType.AccountKey => "accountkey",
        ManifestKeyType.GrantKey => "grantkey",
        _ => throw new ArgumentOutOfRangeException(nameof(type), type, "Unknown ManifestKeyType."),
    };

    /// <summary>
    /// Parses a token.
    /// </summary>
    /// <param name="token">The token to parse.</param>
    /// <param name="type">The parsed ManifestKeyType.</param>
    /// <returns>True when the token names a ManifestKeyType this build supports.</returns>
    public static bool TryParse(string? token, out ManifestKeyType type)
    {
        switch (token)
        {
            case "accountkey":
                type = ManifestKeyType.AccountKey;
                return true;
            case "grantkey":
                type = ManifestKeyType.GrantKey;
                return true;
            default:
                type = default;
                return false;
        }
    }

    /// <summary>
    /// Parses a token and returns the ManifestKeyType.
    /// </summary>
    /// <param name="token">The token to parse.</param>
    /// <returns>The parsed ManifestKeyType.</returns>
    public static ManifestKeyType Parse(string? token)
    {
        if (!TryParse(token, out var type))
        {
            throw new ArgumentOutOfRangeException(nameof(token), token, "Unknown ManifestKeyType token.");
        }

        return type;
    }

    /// <summary>
    /// Whether this access path's encrypted VEK is delivered on the manifest itself.
    /// False does not mean the ciphertext is withheld, only that it reaches the client by another route:
    /// an account-key VEK travels in the unlock envelope served by GET /v2/VaultKey/{type}, because the
    /// client must already have derived its KEK before any manifest is worth fetching.
    /// </summary>
    /// <param name="type">The ManifestKeyType to check.</param>
    /// <returns>The flag value for that ManifestKeyType.</returns>
    public static bool VekTravelsWithManifest(ManifestKeyType type) => type switch
    {
        ManifestKeyType.AccountKey => false,
        ManifestKeyType.GrantKey => true,
        _ => throw new ArgumentOutOfRangeException(nameof(type), type, "Unknown ManifestKeyType."),
    };
}
