// <auto-generated />
// This file is auto-generated from core/models/scripts/generate-key-vocabulary.cjs.
// Do not edit this file directly. Run 'core/models/build.sh' (or 'node core/models/scripts/generate-key-vocabulary.cjs') to regenerate.

#nullable enable

namespace AliasVault.Shared.Models.Enums;

/// <summary>
/// Unlock methods a user can enroll. Each enrolled method stores one copy of the user's Account Key,
/// encrypted with a KEK derived from that method's secret.
/// The token is the only persisted and transmitted identifier; the ordinals below are cosmetic.
/// </summary>
public enum UnlockMethodType
{
    /// <summary>
    /// Master password: the KEK is derived from the password via Argon2.
    /// </summary>
    Password = 0,
}

/// <summary>
/// Token conversions for <see cref="UnlockMethodType"/>.
/// </summary>
public static class UnlockMethodTypes
{
    /// <summary>
    /// Returns the wire/storage token for a UnlockMethodType.
    /// </summary>
    /// <param name="type">The UnlockMethodType to convert.</param>
    /// <returns>The token.</returns>
    public static string ToToken(UnlockMethodType type) => type switch
    {
        UnlockMethodType.Password => "password",
        _ => throw new ArgumentOutOfRangeException(nameof(type), type, "Unknown UnlockMethodType."),
    };

    /// <summary>
    /// Parses a token.
    /// </summary>
    /// <param name="token">The token to parse.</param>
    /// <param name="type">The parsed UnlockMethodType.</param>
    /// <returns>True when the token names a UnlockMethodType this build supports.</returns>
    public static bool TryParse(string? token, out UnlockMethodType type)
    {
        switch (token)
        {
            case "password":
                type = UnlockMethodType.Password;
                return true;
            default:
                type = default;
                return false;
        }
    }

    /// <summary>
    /// Parses a token and returns the UnlockMethodType.
    /// </summary>
    /// <param name="token">The token to parse.</param>
    /// <returns>The parsed UnlockMethodType.</returns>
    public static UnlockMethodType Parse(string? token)
    {
        if (!TryParse(token, out var type))
        {
            throw new ArgumentOutOfRangeException(nameof(token), token, "Unknown UnlockMethodType token.");
        }

        return type;
    }
}
