// <auto-generated>
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AliasClientDb.Migrations
{
    /// <inheritdoc />
    public partial class _231ScopedReferenceCopies : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                @"INSERT OR IGNORE INTO Tags (ManifestId, Id, Name, Color, DisplayOrder, CreatedAt, UpdatedAt, IsDeleted)
                  SELECT DISTINCT it.ManifestId, t.Id, t.Name, t.Color, t.DisplayOrder, t.CreatedAt, t.UpdatedAt, t.IsDeleted
                  FROM ItemTags it JOIN Tags t ON t.Id = it.TagId;");

            migrationBuilder.Sql(
                @"INSERT OR IGNORE INTO FieldDefinitions (ManifestId, Id, FieldType, Label, IsMultiValue, IsHidden, EnableHistory, Weight, ApplicableToTypes, CreatedAt, UpdatedAt, IsDeleted)
                  SELECT DISTINCT fv.ManifestId, fd.Id, fd.FieldType, fd.Label, fd.IsMultiValue, fd.IsHidden, fd.EnableHistory, fd.Weight, fd.ApplicableToTypes, fd.CreatedAt, fd.UpdatedAt, fd.IsDeleted
                  FROM FieldValues fv JOIN FieldDefinitions fd ON fd.Id = fv.FieldDefinitionId;");

            migrationBuilder.Sql(
                @"INSERT OR IGNORE INTO FieldDefinitions (ManifestId, Id, FieldType, Label, IsMultiValue, IsHidden, EnableHistory, Weight, ApplicableToTypes, CreatedAt, UpdatedAt, IsDeleted)
                  SELECT DISTINCT fh.ManifestId, fd.Id, fd.FieldType, fd.Label, fd.IsMultiValue, fd.IsHidden, fd.EnableHistory, fd.Weight, fd.ApplicableToTypes, fd.CreatedAt, fd.UpdatedAt, fd.IsDeleted
                  FROM FieldHistories fh JOIN FieldDefinitions fd ON fd.Id = fh.FieldDefinitionId;");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // The copies are indistinguishable from rows the user created; nothing to undo safely.
        }
    }
}
