// <auto-generated>
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AliasClientDb.Migrations
{
    /// <inheritdoc />
    public partial class _2110RestoreFieldValueColumnDefaults : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            /*
             * FieldValues is rebuilt to re-declare the defaults, and the trigger names that table: SQLite reparses
             * every trigger while it rebuilds, so one naming a momentarily dropped table aborts the whole script.
             * The SQLite provider emits a rebuild after the migration's own statements, so the trigger cannot be
             * restored here; the next migration does it.
             */
            migrationBuilder.Sql(ItemChildManifestTriggerSql.Drop);

            migrationBuilder.AlterColumn<int>(
                name: "ValueIndex",
                table: "FieldValues",
                type: "INTEGER",
                nullable: false,
                defaultValue: 0,
                oldClrType: typeof(int),
                oldType: "INTEGER");

            migrationBuilder.AlterColumn<bool>(
                name: "IsDisabled",
                table: "FieldValues",
                type: "INTEGER",
                nullable: false,
                defaultValue: false,
                oldClrType: typeof(bool),
                oldType: "INTEGER");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<int>(
                name: "ValueIndex",
                table: "FieldValues",
                type: "INTEGER",
                nullable: false,
                oldClrType: typeof(int),
                oldType: "INTEGER",
                oldDefaultValue: 0);

            migrationBuilder.AlterColumn<bool>(
                name: "IsDisabled",
                table: "FieldValues",
                type: "INTEGER",
                nullable: false,
                oldClrType: typeof(bool),
                oldType: "INTEGER",
                oldDefaultValue: false);
        }
    }
}
