// <auto-generated>
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AliasClientDb.Migrations
{
    /// <inheritdoc />
    public partial class _250AddItemStats : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "ItemStats",
                columns: table => new
                {
                    ManifestId = table.Column<Guid>(type: "TEXT", nullable: false),
                    Id = table.Column<Guid>(type: "TEXT", nullable: false),
                    LastUsedAt = table.Column<DateTime>(type: "TEXT", nullable: true),
                    UseCount = table.Column<int>(type: "INTEGER", nullable: false),
                    LastAutofilledAt = table.Column<DateTime>(type: "TEXT", nullable: true),
                    AutofillCount = table.Column<int>(type: "INTEGER", nullable: false),
                    LastCopiedAt = table.Column<DateTime>(type: "TEXT", nullable: true),
                    CopyCount = table.Column<int>(type: "INTEGER", nullable: false),
                    LastPasskeyAuthAt = table.Column<DateTime>(type: "TEXT", nullable: true),
                    PasskeyAuthCount = table.Column<int>(type: "INTEGER", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "TEXT", nullable: false),
                    UpdatedAt = table.Column<DateTime>(type: "TEXT", nullable: false),
                    IsDeleted = table.Column<bool>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ItemStats", x => new { x.ManifestId, x.Id });
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ItemStats");
        }
    }
}
