// <auto-generated>
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AliasClientDb.Migrations
{
    /// <inheritdoc />
    public partial class _230ManifestScopedPrimaryKeys : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("PRAGMA foreign_keys = 0;", suppressTransaction: true);

            migrationBuilder.DropForeignKey(
                name: "FK_Attachments_Items_ItemId",
                table: "Attachments");

            migrationBuilder.DropForeignKey(
                name: "FK_FieldHistories_FieldDefinitions_FieldDefinitionId",
                table: "FieldHistories");

            migrationBuilder.DropForeignKey(
                name: "FK_FieldHistories_Items_ItemId",
                table: "FieldHistories");

            migrationBuilder.DropForeignKey(
                name: "FK_FieldValues_FieldDefinitions_FieldDefinitionId",
                table: "FieldValues");

            migrationBuilder.DropForeignKey(
                name: "FK_FieldValues_Items_ItemId",
                table: "FieldValues");

            migrationBuilder.DropForeignKey(
                name: "FK_Folders_Folders_ParentFolderId",
                table: "Folders");

            migrationBuilder.DropForeignKey(
                name: "FK_Items_Folders_FolderId",
                table: "Items");

            migrationBuilder.DropForeignKey(
                name: "FK_Items_Logos_LogoId",
                table: "Items");

            migrationBuilder.DropForeignKey(
                name: "FK_ItemTags_Items_ItemId",
                table: "ItemTags");

            migrationBuilder.DropForeignKey(
                name: "FK_ItemTags_Tags_TagId",
                table: "ItemTags");

            migrationBuilder.DropForeignKey(
                name: "FK_Passkeys_Items_ItemId",
                table: "Passkeys");

            migrationBuilder.DropForeignKey(
                name: "FK_TotpCodes_Items_ItemId",
                table: "TotpCodes");

            migrationBuilder.DropPrimaryKey(
                name: "PK_TotpCodes",
                table: "TotpCodes");

            migrationBuilder.DropIndex(
                name: "IX_TotpCodes_ItemId",
                table: "TotpCodes");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Tags",
                table: "Tags");

            migrationBuilder.DropIndex(
                name: "IX_Tags_Name",
                table: "Tags");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Passkeys",
                table: "Passkeys");

            migrationBuilder.DropIndex(
                name: "IX_Passkeys_ItemId",
                table: "Passkeys");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Logos",
                table: "Logos");

            migrationBuilder.DropPrimaryKey(
                name: "PK_ItemTags",
                table: "ItemTags");

            migrationBuilder.DropIndex(
                name: "IX_ItemTags_ItemId_TagId",
                table: "ItemTags");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Items",
                table: "Items");

            migrationBuilder.DropIndex(
                name: "IX_Items_FolderId",
                table: "Items");

            migrationBuilder.DropIndex(
                name: "IX_Items_LogoId",
                table: "Items");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Folders",
                table: "Folders");

            migrationBuilder.DropPrimaryKey(
                name: "PK_FieldValues",
                table: "FieldValues");

            migrationBuilder.DropPrimaryKey(
                name: "PK_FieldHistories",
                table: "FieldHistories");

            migrationBuilder.DropPrimaryKey(
                name: "PK_FieldDefinitions",
                table: "FieldDefinitions");

            migrationBuilder.DropPrimaryKey(
                name: "PK_EncryptionKeys",
                table: "EncryptionKeys");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Attachments",
                table: "Attachments");

            migrationBuilder.DropIndex(
                name: "IX_Attachments_ItemId",
                table: "Attachments");

            migrationBuilder.AddColumn<Guid>(
                name: "ManifestId",
                table: "TotpCodes",
                type: "TEXT",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));

            migrationBuilder.AddColumn<Guid>(
                name: "ManifestId",
                table: "Tags",
                type: "TEXT",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));

            migrationBuilder.AddColumn<Guid>(
                name: "ManifestId",
                table: "Passkeys",
                type: "TEXT",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));

            migrationBuilder.AlterColumn<Guid>(
                name: "ManifestId",
                table: "Logos",
                type: "TEXT",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"),
                oldClrType: typeof(Guid),
                oldType: "TEXT",
                oldNullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "ManifestId",
                table: "ItemTags",
                type: "TEXT",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));

            migrationBuilder.AlterColumn<Guid>(
                name: "ManifestId",
                table: "Items",
                type: "TEXT",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"),
                oldClrType: typeof(Guid),
                oldType: "TEXT",
                oldNullable: true);

            migrationBuilder.AlterColumn<Guid>(
                name: "ManifestId",
                table: "Folders",
                type: "TEXT",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"),
                oldClrType: typeof(Guid),
                oldType: "TEXT",
                oldNullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "ManifestId",
                table: "FieldValues",
                type: "TEXT",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));

            migrationBuilder.AddColumn<Guid>(
                name: "ManifestId",
                table: "FieldHistories",
                type: "TEXT",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));

            migrationBuilder.AddColumn<Guid>(
                name: "ManifestId",
                table: "FieldDefinitions",
                type: "TEXT",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));

            migrationBuilder.AlterColumn<Guid>(
                name: "ManifestId",
                table: "EncryptionKeys",
                type: "TEXT",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"),
                oldClrType: typeof(Guid),
                oldType: "TEXT",
                oldNullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "ManifestId",
                table: "Attachments",
                type: "TEXT",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));

            migrationBuilder.AddPrimaryKey(
                name: "PK_TotpCodes",
                table: "TotpCodes",
                columns: new[] { "ManifestId", "Id" });

            migrationBuilder.AddPrimaryKey(
                name: "PK_Tags",
                table: "Tags",
                columns: new[] { "ManifestId", "Id" });

            migrationBuilder.AddPrimaryKey(
                name: "PK_Passkeys",
                table: "Passkeys",
                columns: new[] { "ManifestId", "Id" });

            migrationBuilder.AddPrimaryKey(
                name: "PK_Logos",
                table: "Logos",
                columns: new[] { "ManifestId", "Id" });

            migrationBuilder.AddPrimaryKey(
                name: "PK_ItemTags",
                table: "ItemTags",
                columns: new[] { "ManifestId", "Id" });

            migrationBuilder.AddPrimaryKey(
                name: "PK_Items",
                table: "Items",
                columns: new[] { "ManifestId", "Id" });

            migrationBuilder.AddPrimaryKey(
                name: "PK_Folders",
                table: "Folders",
                columns: new[] { "ManifestId", "Id" });

            migrationBuilder.AddPrimaryKey(
                name: "PK_FieldValues",
                table: "FieldValues",
                columns: new[] { "ManifestId", "Id" });

            migrationBuilder.AddPrimaryKey(
                name: "PK_FieldHistories",
                table: "FieldHistories",
                columns: new[] { "ManifestId", "Id" });

            migrationBuilder.AddPrimaryKey(
                name: "PK_FieldDefinitions",
                table: "FieldDefinitions",
                columns: new[] { "ManifestId", "Id" });

            migrationBuilder.AddPrimaryKey(
                name: "PK_EncryptionKeys",
                table: "EncryptionKeys",
                columns: new[] { "ManifestId", "Id" });

            migrationBuilder.AddPrimaryKey(
                name: "PK_Attachments",
                table: "Attachments",
                columns: new[] { "ManifestId", "Id" });

            migrationBuilder.CreateIndex(
                name: "IX_TotpCodes_ManifestId_ItemId",
                table: "TotpCodes",
                columns: new[] { "ManifestId", "ItemId" });

            migrationBuilder.CreateIndex(
                name: "IX_Tags_ManifestId_Name",
                table: "Tags",
                columns: new[] { "ManifestId", "Name" });

            migrationBuilder.CreateIndex(
                name: "IX_Passkeys_ManifestId_ItemId",
                table: "Passkeys",
                columns: new[] { "ManifestId", "ItemId" });

            migrationBuilder.CreateIndex(
                name: "IX_ItemTags_ManifestId_ItemId_TagId",
                table: "ItemTags",
                columns: new[] { "ManifestId", "ItemId", "TagId" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_ItemTags_ManifestId_TagId",
                table: "ItemTags",
                columns: new[] { "ManifestId", "TagId" });

            migrationBuilder.CreateIndex(
                name: "IX_Items_ManifestId_FolderId",
                table: "Items",
                columns: new[] { "ManifestId", "FolderId" });

            migrationBuilder.CreateIndex(
                name: "IX_Items_ManifestId_LogoId",
                table: "Items",
                columns: new[] { "ManifestId", "LogoId" });

            migrationBuilder.CreateIndex(
                name: "IX_Folders_ManifestId_ParentFolderId",
                table: "Folders",
                columns: new[] { "ManifestId", "ParentFolderId" });

            migrationBuilder.CreateIndex(
                name: "IX_FieldValues_ManifestId_FieldDefinitionId",
                table: "FieldValues",
                columns: new[] { "ManifestId", "FieldDefinitionId" });

            migrationBuilder.CreateIndex(
                name: "IX_FieldValues_ManifestId_ItemId",
                table: "FieldValues",
                columns: new[] { "ManifestId", "ItemId" });

            migrationBuilder.CreateIndex(
                name: "IX_FieldHistories_ManifestId_FieldDefinitionId",
                table: "FieldHistories",
                columns: new[] { "ManifestId", "FieldDefinitionId" });

            migrationBuilder.CreateIndex(
                name: "IX_FieldHistories_ManifestId_ItemId",
                table: "FieldHistories",
                columns: new[] { "ManifestId", "ItemId" });

            migrationBuilder.CreateIndex(
                name: "IX_Attachments_ManifestId_ItemId",
                table: "Attachments",
                columns: new[] { "ManifestId", "ItemId" });

            migrationBuilder.AddForeignKey(
                name: "FK_Attachments_Items_ManifestId_ItemId",
                table: "Attachments",
                columns: new[] { "ManifestId", "ItemId" },
                principalTable: "Items",
                principalColumns: new[] { "ManifestId", "Id" },
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_FieldHistories_FieldDefinitions_ManifestId_FieldDefinitionId",
                table: "FieldHistories",
                columns: new[] { "ManifestId", "FieldDefinitionId" },
                principalTable: "FieldDefinitions",
                principalColumns: new[] { "ManifestId", "Id" },
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_FieldHistories_Items_ManifestId_ItemId",
                table: "FieldHistories",
                columns: new[] { "ManifestId", "ItemId" },
                principalTable: "Items",
                principalColumns: new[] { "ManifestId", "Id" },
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_FieldValues_FieldDefinitions_ManifestId_FieldDefinitionId",
                table: "FieldValues",
                columns: new[] { "ManifestId", "FieldDefinitionId" },
                principalTable: "FieldDefinitions",
                principalColumns: new[] { "ManifestId", "Id" },
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_FieldValues_Items_ManifestId_ItemId",
                table: "FieldValues",
                columns: new[] { "ManifestId", "ItemId" },
                principalTable: "Items",
                principalColumns: new[] { "ManifestId", "Id" },
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_Folders_Folders_ManifestId_ParentFolderId",
                table: "Folders",
                columns: new[] { "ManifestId", "ParentFolderId" },
                principalTable: "Folders",
                principalColumns: new[] { "ManifestId", "Id" },
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_Items_Folders_ManifestId_FolderId",
                table: "Items",
                columns: new[] { "ManifestId", "FolderId" },
                principalTable: "Folders",
                principalColumns: new[] { "ManifestId", "Id" });

            migrationBuilder.AddForeignKey(
                name: "FK_Items_Logos_ManifestId_LogoId",
                table: "Items",
                columns: new[] { "ManifestId", "LogoId" },
                principalTable: "Logos",
                principalColumns: new[] { "ManifestId", "Id" });

            migrationBuilder.AddForeignKey(
                name: "FK_ItemTags_Items_ManifestId_ItemId",
                table: "ItemTags",
                columns: new[] { "ManifestId", "ItemId" },
                principalTable: "Items",
                principalColumns: new[] { "ManifestId", "Id" },
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_ItemTags_Tags_ManifestId_TagId",
                table: "ItemTags",
                columns: new[] { "ManifestId", "TagId" },
                principalTable: "Tags",
                principalColumns: new[] { "ManifestId", "Id" },
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_Passkeys_Items_ManifestId_ItemId",
                table: "Passkeys",
                columns: new[] { "ManifestId", "ItemId" },
                principalTable: "Items",
                principalColumns: new[] { "ManifestId", "Id" },
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_TotpCodes_Items_ManifestId_ItemId",
                table: "TotpCodes",
                columns: new[] { "ManifestId", "ItemId" },
                principalTable: "Items",
                principalColumns: new[] { "ManifestId", "Id" },
                onDelete: ReferentialAction.Cascade);

            /*
             * A child row belongs to the manifest of the item it hangs off. The column was added NOT
             * NULL, so every pre-existing row got the default empty guid; put the item's own stamp
             * back before anything reads these rows as a namespace.
             */
            migrationBuilder.Sql(
                @"UPDATE FieldValues SET ManifestId = (SELECT i.ManifestId FROM Items i WHERE i.Id = FieldValues.ItemId)
                  WHERE EXISTS (SELECT 1 FROM Items i WHERE i.Id = FieldValues.ItemId);");

            migrationBuilder.Sql(
                @"UPDATE FieldHistories SET ManifestId = (SELECT i.ManifestId FROM Items i WHERE i.Id = FieldHistories.ItemId)
                  WHERE EXISTS (SELECT 1 FROM Items i WHERE i.Id = FieldHistories.ItemId);");

            migrationBuilder.Sql(
                @"UPDATE ItemTags SET ManifestId = (SELECT i.ManifestId FROM Items i WHERE i.Id = ItemTags.ItemId)
                  WHERE EXISTS (SELECT 1 FROM Items i WHERE i.Id = ItemTags.ItemId);");

            migrationBuilder.Sql(
                @"UPDATE Attachments SET ManifestId = (SELECT i.ManifestId FROM Items i WHERE i.Id = Attachments.ItemId)
                  WHERE EXISTS (SELECT 1 FROM Items i WHERE i.Id = Attachments.ItemId);");

            migrationBuilder.Sql(
                @"UPDATE Passkeys SET ManifestId = (SELECT i.ManifestId FROM Items i WHERE i.Id = Passkeys.ItemId)
                  WHERE EXISTS (SELECT 1 FROM Items i WHERE i.Id = Passkeys.ItemId);");

            migrationBuilder.Sql(
                @"UPDATE TotpCodes SET ManifestId = (SELECT i.ManifestId FROM Items i WHERE i.Id = TotpCodes.ItemId)
                  WHERE EXISTS (SELECT 1 FROM Items i WHERE i.Id = TotpCodes.ItemId);");

            migrationBuilder.Sql(
                @"UPDATE Tags SET ManifestId = (SELECT it.ManifestId FROM ItemTags it WHERE it.TagId = Tags.Id ORDER BY it.ManifestId LIMIT 1)
                  WHERE EXISTS (SELECT 1 FROM ItemTags it WHERE it.TagId = Tags.Id);");

            migrationBuilder.Sql(
                @"UPDATE FieldDefinitions SET ManifestId = (SELECT fv.ManifestId FROM FieldValues fv WHERE fv.FieldDefinitionId = FieldDefinitions.Id ORDER BY fv.ManifestId LIMIT 1)
                  WHERE EXISTS (SELECT 1 FROM FieldValues fv WHERE fv.FieldDefinitionId = FieldDefinitions.Id);");

            // No closing PRAGMA here: the table rebuild the generator appends after every operation
            // above ends with its own "PRAGMA foreign_keys = 1;", which is what restores them.
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("PRAGMA foreign_keys = 0;", suppressTransaction: true);

            migrationBuilder.DropForeignKey(
                name: "FK_Attachments_Items_ManifestId_ItemId",
                table: "Attachments");

            migrationBuilder.DropForeignKey(
                name: "FK_FieldHistories_FieldDefinitions_ManifestId_FieldDefinitionId",
                table: "FieldHistories");

            migrationBuilder.DropForeignKey(
                name: "FK_FieldHistories_Items_ManifestId_ItemId",
                table: "FieldHistories");

            migrationBuilder.DropForeignKey(
                name: "FK_FieldValues_FieldDefinitions_ManifestId_FieldDefinitionId",
                table: "FieldValues");

            migrationBuilder.DropForeignKey(
                name: "FK_FieldValues_Items_ManifestId_ItemId",
                table: "FieldValues");

            migrationBuilder.DropForeignKey(
                name: "FK_Folders_Folders_ManifestId_ParentFolderId",
                table: "Folders");

            migrationBuilder.DropForeignKey(
                name: "FK_Items_Folders_ManifestId_FolderId",
                table: "Items");

            migrationBuilder.DropForeignKey(
                name: "FK_Items_Logos_ManifestId_LogoId",
                table: "Items");

            migrationBuilder.DropForeignKey(
                name: "FK_ItemTags_Items_ManifestId_ItemId",
                table: "ItemTags");

            migrationBuilder.DropForeignKey(
                name: "FK_ItemTags_Tags_ManifestId_TagId",
                table: "ItemTags");

            migrationBuilder.DropForeignKey(
                name: "FK_Passkeys_Items_ManifestId_ItemId",
                table: "Passkeys");

            migrationBuilder.DropForeignKey(
                name: "FK_TotpCodes_Items_ManifestId_ItemId",
                table: "TotpCodes");

            migrationBuilder.DropPrimaryKey(
                name: "PK_TotpCodes",
                table: "TotpCodes");

            migrationBuilder.DropIndex(
                name: "IX_TotpCodes_ManifestId_ItemId",
                table: "TotpCodes");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Tags",
                table: "Tags");

            migrationBuilder.DropIndex(
                name: "IX_Tags_ManifestId_Name",
                table: "Tags");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Passkeys",
                table: "Passkeys");

            migrationBuilder.DropIndex(
                name: "IX_Passkeys_ManifestId_ItemId",
                table: "Passkeys");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Logos",
                table: "Logos");

            migrationBuilder.DropPrimaryKey(
                name: "PK_ItemTags",
                table: "ItemTags");

            migrationBuilder.DropIndex(
                name: "IX_ItemTags_ManifestId_ItemId_TagId",
                table: "ItemTags");

            migrationBuilder.DropIndex(
                name: "IX_ItemTags_ManifestId_TagId",
                table: "ItemTags");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Items",
                table: "Items");

            migrationBuilder.DropIndex(
                name: "IX_Items_ManifestId_FolderId",
                table: "Items");

            migrationBuilder.DropIndex(
                name: "IX_Items_ManifestId_LogoId",
                table: "Items");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Folders",
                table: "Folders");

            migrationBuilder.DropIndex(
                name: "IX_Folders_ManifestId_ParentFolderId",
                table: "Folders");

            migrationBuilder.DropPrimaryKey(
                name: "PK_FieldValues",
                table: "FieldValues");

            migrationBuilder.DropIndex(
                name: "IX_FieldValues_ManifestId_FieldDefinitionId",
                table: "FieldValues");

            migrationBuilder.DropIndex(
                name: "IX_FieldValues_ManifestId_ItemId",
                table: "FieldValues");

            migrationBuilder.DropPrimaryKey(
                name: "PK_FieldHistories",
                table: "FieldHistories");

            migrationBuilder.DropIndex(
                name: "IX_FieldHistories_ManifestId_FieldDefinitionId",
                table: "FieldHistories");

            migrationBuilder.DropIndex(
                name: "IX_FieldHistories_ManifestId_ItemId",
                table: "FieldHistories");

            migrationBuilder.DropPrimaryKey(
                name: "PK_FieldDefinitions",
                table: "FieldDefinitions");

            migrationBuilder.DropPrimaryKey(
                name: "PK_EncryptionKeys",
                table: "EncryptionKeys");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Attachments",
                table: "Attachments");

            migrationBuilder.DropIndex(
                name: "IX_Attachments_ManifestId_ItemId",
                table: "Attachments");

            migrationBuilder.DropColumn(
                name: "ManifestId",
                table: "TotpCodes");

            migrationBuilder.DropColumn(
                name: "ManifestId",
                table: "Tags");

            migrationBuilder.DropColumn(
                name: "ManifestId",
                table: "Passkeys");

            migrationBuilder.DropColumn(
                name: "ManifestId",
                table: "ItemTags");

            migrationBuilder.DropColumn(
                name: "ManifestId",
                table: "FieldValues");

            migrationBuilder.DropColumn(
                name: "ManifestId",
                table: "FieldHistories");

            migrationBuilder.DropColumn(
                name: "ManifestId",
                table: "FieldDefinitions");

            migrationBuilder.DropColumn(
                name: "ManifestId",
                table: "Attachments");

            migrationBuilder.AlterColumn<Guid>(
                name: "ManifestId",
                table: "Logos",
                type: "TEXT",
                nullable: true,
                oldClrType: typeof(Guid),
                oldType: "TEXT");

            migrationBuilder.AlterColumn<Guid>(
                name: "ManifestId",
                table: "Items",
                type: "TEXT",
                nullable: true,
                oldClrType: typeof(Guid),
                oldType: "TEXT");

            migrationBuilder.AlterColumn<Guid>(
                name: "ManifestId",
                table: "Folders",
                type: "TEXT",
                nullable: true,
                oldClrType: typeof(Guid),
                oldType: "TEXT");

            migrationBuilder.AlterColumn<Guid>(
                name: "ManifestId",
                table: "EncryptionKeys",
                type: "TEXT",
                nullable: true,
                oldClrType: typeof(Guid),
                oldType: "TEXT");

            migrationBuilder.AddPrimaryKey(
                name: "PK_TotpCodes",
                table: "TotpCodes",
                column: "Id");

            migrationBuilder.AddPrimaryKey(
                name: "PK_Tags",
                table: "Tags",
                column: "Id");

            migrationBuilder.AddPrimaryKey(
                name: "PK_Passkeys",
                table: "Passkeys",
                column: "Id");

            migrationBuilder.AddPrimaryKey(
                name: "PK_Logos",
                table: "Logos",
                column: "Id");

            migrationBuilder.AddPrimaryKey(
                name: "PK_ItemTags",
                table: "ItemTags",
                column: "Id");

            migrationBuilder.AddPrimaryKey(
                name: "PK_Items",
                table: "Items",
                column: "Id");

            migrationBuilder.AddPrimaryKey(
                name: "PK_Folders",
                table: "Folders",
                column: "Id");

            migrationBuilder.AddPrimaryKey(
                name: "PK_FieldValues",
                table: "FieldValues",
                column: "Id");

            migrationBuilder.AddPrimaryKey(
                name: "PK_FieldHistories",
                table: "FieldHistories",
                column: "Id");

            migrationBuilder.AddPrimaryKey(
                name: "PK_FieldDefinitions",
                table: "FieldDefinitions",
                column: "Id");

            migrationBuilder.AddPrimaryKey(
                name: "PK_EncryptionKeys",
                table: "EncryptionKeys",
                column: "Id");

            migrationBuilder.AddPrimaryKey(
                name: "PK_Attachments",
                table: "Attachments",
                column: "Id");

            migrationBuilder.CreateIndex(
                name: "IX_TotpCodes_ItemId",
                table: "TotpCodes",
                column: "ItemId");

            migrationBuilder.CreateIndex(
                name: "IX_Tags_Name",
                table: "Tags",
                column: "Name");

            migrationBuilder.CreateIndex(
                name: "IX_Passkeys_ItemId",
                table: "Passkeys",
                column: "ItemId");

            migrationBuilder.CreateIndex(
                name: "IX_ItemTags_ItemId_TagId",
                table: "ItemTags",
                columns: new[] { "ItemId", "TagId" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_Items_FolderId",
                table: "Items",
                column: "FolderId");

            migrationBuilder.CreateIndex(
                name: "IX_Items_LogoId",
                table: "Items",
                column: "LogoId");

            migrationBuilder.CreateIndex(
                name: "IX_Attachments_ItemId",
                table: "Attachments",
                column: "ItemId");

            migrationBuilder.AddForeignKey(
                name: "FK_Attachments_Items_ItemId",
                table: "Attachments",
                column: "ItemId",
                principalTable: "Items",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_FieldHistories_FieldDefinitions_FieldDefinitionId",
                table: "FieldHistories",
                column: "FieldDefinitionId",
                principalTable: "FieldDefinitions",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_FieldHistories_Items_ItemId",
                table: "FieldHistories",
                column: "ItemId",
                principalTable: "Items",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_FieldValues_FieldDefinitions_FieldDefinitionId",
                table: "FieldValues",
                column: "FieldDefinitionId",
                principalTable: "FieldDefinitions",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_FieldValues_Items_ItemId",
                table: "FieldValues",
                column: "ItemId",
                principalTable: "Items",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_Folders_Folders_ParentFolderId",
                table: "Folders",
                column: "ParentFolderId",
                principalTable: "Folders",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_Items_Folders_FolderId",
                table: "Items",
                column: "FolderId",
                principalTable: "Folders",
                principalColumn: "Id",
                onDelete: ReferentialAction.SetNull);

            migrationBuilder.AddForeignKey(
                name: "FK_Items_Logos_LogoId",
                table: "Items",
                column: "LogoId",
                principalTable: "Logos",
                principalColumn: "Id",
                onDelete: ReferentialAction.SetNull);

            migrationBuilder.AddForeignKey(
                name: "FK_ItemTags_Items_ItemId",
                table: "ItemTags",
                column: "ItemId",
                principalTable: "Items",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_ItemTags_Tags_TagId",
                table: "ItemTags",
                column: "TagId",
                principalTable: "Tags",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_Passkeys_Items_ItemId",
                table: "Passkeys",
                column: "ItemId",
                principalTable: "Items",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_TotpCodes_Items_ItemId",
                table: "TotpCodes",
                column: "ItemId",
                principalTable: "Items",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
