// <auto-generated>
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AliasClientDb.Migrations
{
    /// <inheritdoc />
    public partial class _217RestoreItemChildManifestTrigger : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Previous migration dropped the trigger in order to rebuild the ItemTags table with the new primary key, now we restore it.
            migrationBuilder.Sql(ItemChildManifestTriggerSql.Create);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(ItemChildManifestTriggerSql.Drop);
        }
    }
}
