// <auto-generated>
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AliasClientDb.Migrations
{
    /// <inheritdoc />
    public partial class _211ItemChildManifestTrigger : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            /*
             * Moving an item between folders can move it between manifests, and every row owned by that item
             * has to follow it: those rows reference their item by the composite (ManifestId, ItemId), so a stamp
             * left behind points at nothing and the item silently loses its fields, TOTP codes and attachments in
             * every local read until the next push heals it server-side. This trigger ensures all clients that
             * use this sqlite structure will automatically re-stamp when an item is moved between manifests.
             */
            migrationBuilder.Sql(ItemChildManifestTriggerSql.Create);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(ItemChildManifestTriggerSql.Drop);
        }
    }
}
