// <auto-generated>
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AliasClientDb.Migrations
{
    /// <inheritdoc />
    public partial class _211ItemChildManifestTrigger : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            /*
             * The triggers keep item-scoped rows stamped with their item's manifest. They live in their own migration
             * and cannot be squashed into the previous one: the SQLite provider emits its table rebuilds after the
             * migration's own statements, dropping a table drops its triggers (the Items rebuild would silently
             * discard them), and SQLite reparses the remaining triggers during a rebuild, aborting on one that
             * names a momentarily dropped table.
             */
            migrationBuilder.Sql(ItemChildManifestTriggerSql.Create);

            // Restores what the previous migration turned off for its rebuild.
            migrationBuilder.Sql("PRAGMA foreign_keys = ON;", suppressTransaction: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(ItemChildManifestTriggerSql.Drop);
        }
    }
}
