// <auto-generated>
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AliasClientDb.Migrations
{
    /// <inheritdoc />
    public partial class _216ItemTagKeyedByItemAndTag : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropPrimaryKey(
                name: "PK_ItemTags",
                table: "ItemTags");

            migrationBuilder.DropIndex(
                name: "IX_ItemTags_ManifestId_ItemId_TagId",
                table: "ItemTags");

            migrationBuilder.DropColumn(
                name: "Id",
                table: "ItemTags");

            migrationBuilder.AddPrimaryKey(
                name: "PK_ItemTags",
                table: "ItemTags",
                columns: new[] { "ManifestId", "ItemId", "TagId" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropPrimaryKey(
                name: "PK_ItemTags",
                table: "ItemTags");

            migrationBuilder.AddColumn<Guid>(
                name: "Id",
                table: "ItemTags",
                type: "TEXT",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));

            migrationBuilder.AddPrimaryKey(
                name: "PK_ItemTags",
                table: "ItemTags",
                columns: new[] { "ManifestId", "Id" });

            migrationBuilder.CreateIndex(
                name: "IX_ItemTags_ManifestId_ItemId_TagId",
                table: "ItemTags",
                columns: new[] { "ManifestId", "ItemId", "TagId" },
                unique: true);
        }
    }
}
