// <auto-generated>
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AliasClientDb.Migrations
{
    /// <inheritdoc />
    public partial class _220ScopeEncryptionKeysPerManifest : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<Guid>(
                name: "SharedFolderId",
                table: "EncryptionKeys",
                type: "TEXT",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_EncryptionKeys_SharedFolderId_IsPrimary",
                table: "EncryptionKeys",
                columns: new[] { "SharedFolderId", "IsPrimary" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_EncryptionKeys_SharedFolderId_IsPrimary",
                table: "EncryptionKeys");

            migrationBuilder.DropColumn(
                name: "SharedFolderId",
                table: "EncryptionKeys");
        }
    }
}
