// <auto-generated>
﻿using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AliasClientDb.Migrations
{
    /// <inheritdoc />
    public partial class _210CodecOverflowsAndItemLogos : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_Logos_Source",
                table: "Logos");

            migrationBuilder.AddColumn<string>(
                name: "Kind",
                table: "Logos",
                type: "TEXT",
                maxLength: 20,
                nullable: false,
                defaultValue: "favicon");

            migrationBuilder.AddColumn<string>(
                name: "Name",
                table: "Logos",
                type: "TEXT",
                maxLength: 255,
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "SharedFolderId",
                table: "Logos",
                type: "TEXT",
                nullable: true);

            migrationBuilder.CreateTable(
                name: "CodecOverflows",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "TEXT", nullable: false),
                    Data = table.Column<string>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CodecOverflows", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_Logos_SharedFolderId_Kind_Source",
                table: "Logos",
                columns: new[] { "SharedFolderId", "Kind", "Source" },
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "CodecOverflows");

            migrationBuilder.DropIndex(
                name: "IX_Logos_SharedFolderId_Kind_Source",
                table: "Logos");

            migrationBuilder.DropColumn(
                name: "Kind",
                table: "Logos");

            migrationBuilder.DropColumn(
                name: "Name",
                table: "Logos");

            migrationBuilder.DropColumn(
                name: "SharedFolderId",
                table: "Logos");

            migrationBuilder.CreateIndex(
                name: "IX_Logos_Source",
                table: "Logos",
                column: "Source",
                unique: true);
        }
    }
}
