// <auto-generated>
﻿using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AliasClientDb.Migrations
{
    /// <inheritdoc />
    public partial class _220ScopeLogosPerManifest : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_Logos_Source",
                table: "Logos");

            migrationBuilder.AddColumn<Guid>(
                name: "SharedFolderId",
                table: "Logos",
                type: "TEXT",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_Logos_SharedFolderId_Source",
                table: "Logos",
                columns: new[] { "SharedFolderId", "Source" },
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_Logos_SharedFolderId_Source",
                table: "Logos");

            migrationBuilder.DropColumn(
                name: "SharedFolderId",
                table: "Logos");

            migrationBuilder.CreateIndex(
                name: "IX_Logos_Source",
                table: "Logos",
                column: "Source",
                unique: true);
        }
    }
}
