//! Client-facing defaults for the password/passphrase generator.
//!
//! @generated — do NOT edit this file directly. It is generated from
//! core/models/src/defaults/PasswordGeneratorDefaults.ts by core/models/scripts/generate-password-defaults.cjs.
//! Edit the TypeScript source and run 'core/models/build.sh' to regenerate.

/// Default length of a generated basic password.
pub const DEFAULT_PASSWORD_LENGTH: u32 = 18;

/// Minimum password length offered by the UI length slider.
pub const MIN_PASSWORD_LENGTH: u32 = 8;

/// Maximum password length (also the hard cap enforced by the generator).
pub const MAX_PASSWORD_LENGTH: u32 = 256;

/// Default number of words in a generated Diceware passphrase.
pub const DEFAULT_WORD_COUNT: u32 = 5;

/// Minimum number of words offered by the UI word-count slider.
pub const MIN_WORD_COUNT: u32 = 3;

/// Maximum number of words (also the hard cap enforced by the generator).
pub const MAX_WORD_COUNT: u32 = 10;
