remote_theme: just-the-docs/just-the-docs
title: AliasVault
description: Documentation for the AliasVault password manager

logo: "/assets/img/logo.svg"
favicon_ico: "/assets/img/favicon.png"

# Navigation settings
aux_links:
  "AliasVault on GitHub":
    - "https://github.com/aliasvault/aliasvault"
  "AliasVault Website":
    - "https://aliasvault.net"
aux_links_new_tab: true

# Search settings
search_enabled: true
heading_anchors: true

# Theme settings
color_scheme: aliasvault

# Enable copy code button
enable_copy_code_button: true

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/aliasvault/aliasvault" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: purple
