import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * The sidebar is generated automatically from the folder structure under
 * `docs/`. Ordering and category labels are controlled by `_category_.json`
 * files and the `sidebar_position` frontmatter on each page.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
